/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { PairType, InstantiateMsg, PairConfig, TrackerConfig, ExecuteMsg, AssetInfo, Addr, Binary, QueryMsg, ArrayOfPairType, ConfigResponse, FeeInfoResponse, PairInfo, PairsResponse } from "./AstroportFactory.types";
import { AstroportFactoryQueryClient, AstroportFactoryClient } from "./AstroportFactory.client";
export const astroportFactoryQueryKeys = {
  contract: ([{
    contract: "astroportFactory"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportFactoryQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportFactoryQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  pair: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportFactoryQueryKeys.address(contractAddress)[0],
    method: "pair",
    args
  }] as const),
  pairs: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportFactoryQueryKeys.address(contractAddress)[0],
    method: "pairs",
    args
  }] as const),
  feeInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportFactoryQueryKeys.address(contractAddress)[0],
    method: "fee_info",
    args
  }] as const),
  blacklistedPairTypes: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportFactoryQueryKeys.address(contractAddress)[0],
    method: "blacklisted_pair_types",
    args
  }] as const),
  trackerConfig: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportFactoryQueryKeys.address(contractAddress)[0],
    method: "tracker_config",
    args
  }] as const)
};
export const astroportFactoryQueries = {
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportFactoryConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportFactoryQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pair: <TData = PairInfo,>({
    client,
    args,
    options
  }: AstroportFactoryPairQuery<TData>): UseQueryOptions<PairInfo, Error, TData> => ({
    queryKey: astroportFactoryQueryKeys.pair(client?.contractAddress, args),
    queryFn: () => client ? client.pair({
      assetInfos: args.assetInfos
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pairs: <TData = PairsResponse,>({
    client,
    args,
    options
  }: AstroportFactoryPairsQuery<TData>): UseQueryOptions<PairsResponse, Error, TData> => ({
    queryKey: astroportFactoryQueryKeys.pairs(client?.contractAddress, args),
    queryFn: () => client ? client.pairs({
      limit: args.limit,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  feeInfo: <TData = FeeInfoResponse,>({
    client,
    args,
    options
  }: AstroportFactoryFeeInfoQuery<TData>): UseQueryOptions<FeeInfoResponse, Error, TData> => ({
    queryKey: astroportFactoryQueryKeys.feeInfo(client?.contractAddress, args),
    queryFn: () => client ? client.feeInfo({
      pairType: args.pairType
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  blacklistedPairTypes: <TData = ArrayOfPairType,>({
    client,
    options
  }: AstroportFactoryBlacklistedPairTypesQuery<TData>): UseQueryOptions<ArrayOfPairType, Error, TData> => ({
    queryKey: astroportFactoryQueryKeys.blacklistedPairTypes(client?.contractAddress),
    queryFn: () => client ? client.blacklistedPairTypes() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  trackerConfig: <TData = TrackerConfig,>({
    client,
    options
  }: AstroportFactoryTrackerConfigQuery<TData>): UseQueryOptions<TrackerConfig, Error, TData> => ({
    queryKey: astroportFactoryQueryKeys.trackerConfig(client?.contractAddress),
    queryFn: () => client ? client.trackerConfig() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportFactoryReactQuery<TResponse, TData = TResponse> {
  client: AstroportFactoryQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportFactoryTrackerConfigQuery<TData> extends AstroportFactoryReactQuery<TrackerConfig, TData> {}
export function useAstroportFactoryTrackerConfigQuery<TData = TrackerConfig>({
  client,
  options
}: AstroportFactoryTrackerConfigQuery<TData>) {
  return useQuery<TrackerConfig, Error, TData>(astroportFactoryQueryKeys.trackerConfig(client?.contractAddress), () => client ? client.trackerConfig() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportFactoryBlacklistedPairTypesQuery<TData> extends AstroportFactoryReactQuery<ArrayOfPairType, TData> {}
export function useAstroportFactoryBlacklistedPairTypesQuery<TData = ArrayOfPairType>({
  client,
  options
}: AstroportFactoryBlacklistedPairTypesQuery<TData>) {
  return useQuery<ArrayOfPairType, Error, TData>(astroportFactoryQueryKeys.blacklistedPairTypes(client?.contractAddress), () => client ? client.blacklistedPairTypes() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportFactoryFeeInfoQuery<TData> extends AstroportFactoryReactQuery<FeeInfoResponse, TData> {
  args: {
    pairType: PairType;
  };
}
export function useAstroportFactoryFeeInfoQuery<TData = FeeInfoResponse>({
  client,
  args,
  options
}: AstroportFactoryFeeInfoQuery<TData>) {
  return useQuery<FeeInfoResponse, Error, TData>(astroportFactoryQueryKeys.feeInfo(client?.contractAddress, args), () => client ? client.feeInfo({
    pairType: args.pairType
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportFactoryPairsQuery<TData> extends AstroportFactoryReactQuery<PairsResponse, TData> {
  args: {
    limit?: number;
    startAfter?: AssetInfo[];
  };
}
export function useAstroportFactoryPairsQuery<TData = PairsResponse>({
  client,
  args,
  options
}: AstroportFactoryPairsQuery<TData>) {
  return useQuery<PairsResponse, Error, TData>(astroportFactoryQueryKeys.pairs(client?.contractAddress, args), () => client ? client.pairs({
    limit: args.limit,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportFactoryPairQuery<TData> extends AstroportFactoryReactQuery<PairInfo, TData> {
  args: {
    assetInfos: AssetInfo[];
  };
}
export function useAstroportFactoryPairQuery<TData = PairInfo>({
  client,
  args,
  options
}: AstroportFactoryPairQuery<TData>) {
  return useQuery<PairInfo, Error, TData>(astroportFactoryQueryKeys.pair(client?.contractAddress, args), () => client ? client.pair({
    assetInfos: args.assetInfos
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportFactoryConfigQuery<TData> extends AstroportFactoryReactQuery<ConfigResponse, TData> {}
export function useAstroportFactoryConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportFactoryConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportFactoryQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportFactoryClaimOwnershipMutation {
  client: AstroportFactoryClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportFactoryDropOwnershipProposalMutation {
  client: AstroportFactoryClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportFactoryProposeNewOwnerMutation {
  client: AstroportFactoryClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportFactoryDeregisterMutation {
  client: AstroportFactoryClient;
  msg: {
    assetInfos: AssetInfo[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryDeregisterMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryDeregisterMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryDeregisterMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.deregister(msg, fee, memo, funds), options);
}
export interface AstroportFactoryCreatePairMutation {
  client: AstroportFactoryClient;
  msg: {
    assetInfos: AssetInfo[];
    initParams?: Binary;
    pairType: PairType;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryCreatePairMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryCreatePairMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryCreatePairMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.createPair(msg, fee, memo, funds), options);
}
export interface AstroportFactoryUpdatePairConfigMutation {
  client: AstroportFactoryClient;
  msg: {
    config: PairConfig;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryUpdatePairConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryUpdatePairConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryUpdatePairConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updatePairConfig(msg, fee, memo, funds), options);
}
export interface AstroportFactoryUpdateTrackerConfigMutation {
  client: AstroportFactoryClient;
  msg: {
    tokenFactoryAddr?: string;
    trackerCodeId: number;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryUpdateTrackerConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryUpdateTrackerConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryUpdateTrackerConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateTrackerConfig(msg, fee, memo, funds), options);
}
export interface AstroportFactoryUpdateConfigMutation {
  client: AstroportFactoryClient;
  msg: {
    coinRegistryAddress?: string;
    feeAddress?: string;
    generatorAddress?: string;
    tokenCodeId?: number;
    whitelistCodeId?: number;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportFactoryUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportFactoryUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportFactoryUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}