/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { PairType, InstantiateMsg, PairConfig, TrackerConfig, ExecuteMsg, AssetInfo, Addr, Binary, QueryMsg, ArrayOfPairType, ConfigResponse, FeeInfoResponse, PairInfo, PairsResponse } from "./AstroportFactory.types";
export interface AstroportFactoryReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  pair: ({
    assetInfos
  }: {
    assetInfos: AssetInfo[];
  }) => Promise<PairInfo>;
  pairs: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: AssetInfo[];
  }) => Promise<PairsResponse>;
  feeInfo: ({
    pairType
  }: {
    pairType: PairType;
  }) => Promise<FeeInfoResponse>;
  blacklistedPairTypes: () => Promise<ArrayOfPairType>;
  trackerConfig: () => Promise<TrackerConfig>;
}
export class AstroportFactoryQueryClient implements AstroportFactoryReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.pair = this.pair.bind(this);
    this.pairs = this.pairs.bind(this);
    this.feeInfo = this.feeInfo.bind(this);
    this.blacklistedPairTypes = this.blacklistedPairTypes.bind(this);
    this.trackerConfig = this.trackerConfig.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  pair = async ({
    assetInfos
  }: {
    assetInfos: AssetInfo[];
  }): Promise<PairInfo> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pair: {
        asset_infos: assetInfos
      }
    });
  };
  pairs = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: AssetInfo[];
  }): Promise<PairsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      pairs: {
        limit,
        start_after: startAfter
      }
    });
  };
  feeInfo = async ({
    pairType
  }: {
    pairType: PairType;
  }): Promise<FeeInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      fee_info: {
        pair_type: pairType
      }
    });
  };
  blacklistedPairTypes = async (): Promise<ArrayOfPairType> => {
    return this.client.queryContractSmart(this.contractAddress, {
      blacklisted_pair_types: {}
    });
  };
  trackerConfig = async (): Promise<TrackerConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      tracker_config: {}
    });
  };
}
export interface AstroportFactoryInterface {
  contractAddress: string;
  sender: string;
  updateConfig: ({
    coinRegistryAddress,
    feeAddress,
    generatorAddress,
    tokenCodeId,
    whitelistCodeId
  }: {
    coinRegistryAddress?: string;
    feeAddress?: string;
    generatorAddress?: string;
    tokenCodeId?: number;
    whitelistCodeId?: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateTrackerConfig: ({
    tokenFactoryAddr,
    trackerCodeId
  }: {
    tokenFactoryAddr?: string;
    trackerCodeId: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updatePairConfig: ({
    config
  }: {
    config: PairConfig;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  createPair: ({
    assetInfos,
    initParams,
    pairType
  }: {
    assetInfos: AssetInfo[];
    initParams?: Binary;
    pairType: PairType;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  deregister: ({
    assetInfos
  }: {
    assetInfos: AssetInfo[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  proposeNewOwner: ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  dropOwnershipProposal: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  claimOwnership: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroportFactoryClient implements AstroportFactoryInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.updateConfig = this.updateConfig.bind(this);
    this.updateTrackerConfig = this.updateTrackerConfig.bind(this);
    this.updatePairConfig = this.updatePairConfig.bind(this);
    this.createPair = this.createPair.bind(this);
    this.deregister = this.deregister.bind(this);
    this.proposeNewOwner = this.proposeNewOwner.bind(this);
    this.dropOwnershipProposal = this.dropOwnershipProposal.bind(this);
    this.claimOwnership = this.claimOwnership.bind(this);
  }
  updateConfig = async ({
    coinRegistryAddress,
    feeAddress,
    generatorAddress,
    tokenCodeId,
    whitelistCodeId
  }: {
    coinRegistryAddress?: string;
    feeAddress?: string;
    generatorAddress?: string;
    tokenCodeId?: number;
    whitelistCodeId?: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        coin_registry_address: coinRegistryAddress,
        fee_address: feeAddress,
        generator_address: generatorAddress,
        token_code_id: tokenCodeId,
        whitelist_code_id: whitelistCodeId
      }
    }, fee_, memo_, funds_);
  };
  updateTrackerConfig = async ({
    tokenFactoryAddr,
    trackerCodeId
  }: {
    tokenFactoryAddr?: string;
    trackerCodeId: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_tracker_config: {
        token_factory_addr: tokenFactoryAddr,
        tracker_code_id: trackerCodeId
      }
    }, fee_, memo_, funds_);
  };
  updatePairConfig = async ({
    config
  }: {
    config: PairConfig;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_pair_config: {
        config
      }
    }, fee_, memo_, funds_);
  };
  createPair = async ({
    assetInfos,
    initParams,
    pairType
  }: {
    assetInfos: AssetInfo[];
    initParams?: Binary;
    pairType: PairType;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_pair: {
        asset_infos: assetInfos,
        init_params: initParams,
        pair_type: pairType
      }
    }, fee_, memo_, funds_);
  };
  deregister = async ({
    assetInfos
  }: {
    assetInfos: AssetInfo[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deregister: {
        asset_infos: assetInfos
      }
    }, fee_, memo_, funds_);
  };
  proposeNewOwner = async ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      propose_new_owner: {
        expires_in: expiresIn,
        owner
      }
    }, fee_, memo_, funds_);
  };
  dropOwnershipProposal = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      drop_ownership_proposal: {}
    }, fee_, memo_, funds_);
  };
  claimOwnership = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_ownership: {}
    }, fee_, memo_, funds_);
  };
}