/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, InstantiateMsg, ExecuteMsg, Uint128, Binary, Cw20ReceiveMsg, VestingAccount, VestingSchedule, VestingSchedulePoint, QueryMsg, OrderBy, MigrateMsg, ConfigResponse, Uint64, VestingAccountResponse, VestingInfo, VestingAccountsResponse } from "./AstroportVesting.types";
import { AstroportVestingQueryClient, AstroportVestingClient } from "./AstroportVesting.client";
export const astroportVestingQueryKeys = {
  contract: ([{
    contract: "astroportVesting"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportVestingQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportVestingQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  vestingAccount: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportVestingQueryKeys.address(contractAddress)[0],
    method: "vesting_account",
    args
  }] as const),
  vestingAccounts: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportVestingQueryKeys.address(contractAddress)[0],
    method: "vesting_accounts",
    args
  }] as const),
  availableAmount: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportVestingQueryKeys.address(contractAddress)[0],
    method: "available_amount",
    args
  }] as const),
  timestamp: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportVestingQueryKeys.address(contractAddress)[0],
    method: "timestamp",
    args
  }] as const)
};
export const astroportVestingQueries = {
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportVestingConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportVestingQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  vestingAccount: <TData = VestingAccountResponse,>({
    client,
    args,
    options
  }: AstroportVestingVestingAccountQuery<TData>): UseQueryOptions<VestingAccountResponse, Error, TData> => ({
    queryKey: astroportVestingQueryKeys.vestingAccount(client?.contractAddress, args),
    queryFn: () => client ? client.vestingAccount({
      address: args.address
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  vestingAccounts: <TData = VestingAccountsResponse,>({
    client,
    args,
    options
  }: AstroportVestingVestingAccountsQuery<TData>): UseQueryOptions<VestingAccountsResponse, Error, TData> => ({
    queryKey: astroportVestingQueryKeys.vestingAccounts(client?.contractAddress, args),
    queryFn: () => client ? client.vestingAccounts({
      limit: args.limit,
      orderBy: args.orderBy,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  availableAmount: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportVestingAvailableAmountQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportVestingQueryKeys.availableAmount(client?.contractAddress, args),
    queryFn: () => client ? client.availableAmount({
      address: args.address
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  timestamp: <TData = Uint64,>({
    client,
    options
  }: AstroportVestingTimestampQuery<TData>): UseQueryOptions<Uint64, Error, TData> => ({
    queryKey: astroportVestingQueryKeys.timestamp(client?.contractAddress),
    queryFn: () => client ? client.timestamp() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportVestingReactQuery<TResponse, TData = TResponse> {
  client: AstroportVestingQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportVestingTimestampQuery<TData> extends AstroportVestingReactQuery<Uint64, TData> {}
export function useAstroportVestingTimestampQuery<TData = Uint64>({
  client,
  options
}: AstroportVestingTimestampQuery<TData>) {
  return useQuery<Uint64, Error, TData>(astroportVestingQueryKeys.timestamp(client?.contractAddress), () => client ? client.timestamp() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportVestingAvailableAmountQuery<TData> extends AstroportVestingReactQuery<Uint128, TData> {
  args: {
    address: string;
  };
}
export function useAstroportVestingAvailableAmountQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportVestingAvailableAmountQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportVestingQueryKeys.availableAmount(client?.contractAddress, args), () => client ? client.availableAmount({
    address: args.address
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportVestingVestingAccountsQuery<TData> extends AstroportVestingReactQuery<VestingAccountsResponse, TData> {
  args: {
    limit?: number;
    orderBy?: OrderBy;
    startAfter?: string;
  };
}
export function useAstroportVestingVestingAccountsQuery<TData = VestingAccountsResponse>({
  client,
  args,
  options
}: AstroportVestingVestingAccountsQuery<TData>) {
  return useQuery<VestingAccountsResponse, Error, TData>(astroportVestingQueryKeys.vestingAccounts(client?.contractAddress, args), () => client ? client.vestingAccounts({
    limit: args.limit,
    orderBy: args.orderBy,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportVestingVestingAccountQuery<TData> extends AstroportVestingReactQuery<VestingAccountResponse, TData> {
  args: {
    address: string;
  };
}
export function useAstroportVestingVestingAccountQuery<TData = VestingAccountResponse>({
  client,
  args,
  options
}: AstroportVestingVestingAccountQuery<TData>) {
  return useQuery<VestingAccountResponse, Error, TData>(astroportVestingQueryKeys.vestingAccount(client?.contractAddress, args), () => client ? client.vestingAccount({
    address: args.address
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportVestingConfigQuery<TData> extends AstroportVestingReactQuery<ConfigResponse, TData> {}
export function useAstroportVestingConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportVestingConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportVestingQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportVestingClaimOwnershipMutation {
  client: AstroportVestingClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportVestingClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportVestingClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportVestingClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportVestingDropOwnershipProposalMutation {
  client: AstroportVestingClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportVestingDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportVestingDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportVestingDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportVestingProposeNewOwnerMutation {
  client: AstroportVestingClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportVestingProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportVestingProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportVestingProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportVestingWithdrawFromActiveScheduleMutation {
  client: AstroportVestingClient;
  msg: {
    account: string;
    recipient?: string;
    withdrawAmount: Uint128;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportVestingWithdrawFromActiveScheduleMutation(options?: Omit<UseMutationOptions<any, Error, AstroportVestingWithdrawFromActiveScheduleMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportVestingWithdrawFromActiveScheduleMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.withdrawFromActiveSchedule(msg, fee, memo, funds), options);
}
export interface AstroportVestingRegisterVestingAccountsMutation {
  client: AstroportVestingClient;
  msg: {
    vestingAccounts: VestingAccount[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportVestingRegisterVestingAccountsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportVestingRegisterVestingAccountsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportVestingRegisterVestingAccountsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.registerVestingAccounts(msg, fee, memo, funds), options);
}
export interface AstroportVestingReceiveMutation {
  client: AstroportVestingClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportVestingReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportVestingReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportVestingReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}
export interface AstroportVestingClaimMutation {
  client: AstroportVestingClient;
  msg: {
    amount?: Uint128;
    recipient?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportVestingClaimMutation(options?: Omit<UseMutationOptions<any, Error, AstroportVestingClaimMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportVestingClaimMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claim(msg, fee, memo, funds), options);
}