/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { AssetInfo, Addr, Uint64, Decimal, InstantiateMsg, SecondReceiverParams, ExecuteMsg, Uint128, UpdateAddr, AssetWithLimit, UpdateDevFundConfig, DevFundConfig, QueryMsg, MigrateMsg, BalancesResponse, Asset, ArrayOfTupleOfStringAndString, ConfigResponse, SecondReceiverConfig, SeizeConfig } from "./AstroportMaker.types";
export interface AstroportMakerReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  balances: ({
    assets
  }: {
    assets: AssetInfo[];
  }) => Promise<BalancesResponse>;
  bridges: () => Promise<ArrayOfTupleOfStringAndString>;
  querySeizeConfig: () => Promise<SeizeConfig>;
}
export class AstroportMakerQueryClient implements AstroportMakerReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.balances = this.balances.bind(this);
    this.bridges = this.bridges.bind(this);
    this.querySeizeConfig = this.querySeizeConfig.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  balances = async ({
    assets
  }: {
    assets: AssetInfo[];
  }): Promise<BalancesResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balances: {
        assets
      }
    });
  };
  bridges = async (): Promise<ArrayOfTupleOfStringAndString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      bridges: {}
    });
  };
  querySeizeConfig = async (): Promise<SeizeConfig> => {
    return this.client.queryContractSmart(this.contractAddress, {
      query_seize_config: {}
    });
  };
}
export interface AstroportMakerInterface {
  contractAddress: string;
  sender: string;
  collect: ({
    assets
  }: {
    assets: AssetWithLimit[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateConfig: ({
    astroToken,
    basicAsset,
    collectCooldown,
    devFundConfig,
    factoryContract,
    governanceContract,
    governancePercent,
    maxSpread,
    secondReceiverParams,
    stakingContract
  }: {
    astroToken?: AssetInfo;
    basicAsset?: AssetInfo;
    collectCooldown?: number;
    devFundConfig?: UpdateDevFundConfig;
    factoryContract?: string;
    governanceContract?: UpdateAddr;
    governancePercent?: Uint64;
    maxSpread?: Decimal;
    secondReceiverParams?: SecondReceiverParams;
    stakingContract?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateBridges: ({
    add,
    remove
  }: {
    add?: AssetInfo[][][];
    remove?: AssetInfo[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  swapBridgeAssets: ({
    assets,
    depth
  }: {
    assets: AssetInfo[];
    depth: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  distributeAstro: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  proposeNewOwner: ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  dropOwnershipProposal: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  claimOwnership: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  enableRewards: ({
    blocks
  }: {
    blocks: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  seize: ({
    assets
  }: {
    assets: AssetWithLimit[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateSeizeConfig: ({
    receiver,
    seizableAssets
  }: {
    receiver?: string;
    seizableAssets?: AssetInfo[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroportMakerClient implements AstroportMakerInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.collect = this.collect.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.updateBridges = this.updateBridges.bind(this);
    this.swapBridgeAssets = this.swapBridgeAssets.bind(this);
    this.distributeAstro = this.distributeAstro.bind(this);
    this.proposeNewOwner = this.proposeNewOwner.bind(this);
    this.dropOwnershipProposal = this.dropOwnershipProposal.bind(this);
    this.claimOwnership = this.claimOwnership.bind(this);
    this.enableRewards = this.enableRewards.bind(this);
    this.seize = this.seize.bind(this);
    this.updateSeizeConfig = this.updateSeizeConfig.bind(this);
  }
  collect = async ({
    assets
  }: {
    assets: AssetWithLimit[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      collect: {
        assets
      }
    }, fee_, memo_, funds_);
  };
  updateConfig = async ({
    astroToken,
    basicAsset,
    collectCooldown,
    devFundConfig,
    factoryContract,
    governanceContract,
    governancePercent,
    maxSpread,
    secondReceiverParams,
    stakingContract
  }: {
    astroToken?: AssetInfo;
    basicAsset?: AssetInfo;
    collectCooldown?: number;
    devFundConfig?: UpdateDevFundConfig;
    factoryContract?: string;
    governanceContract?: UpdateAddr;
    governancePercent?: Uint64;
    maxSpread?: Decimal;
    secondReceiverParams?: SecondReceiverParams;
    stakingContract?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        astro_token: astroToken,
        basic_asset: basicAsset,
        collect_cooldown: collectCooldown,
        dev_fund_config: devFundConfig,
        factory_contract: factoryContract,
        governance_contract: governanceContract,
        governance_percent: governancePercent,
        max_spread: maxSpread,
        second_receiver_params: secondReceiverParams,
        staking_contract: stakingContract
      }
    }, fee_, memo_, funds_);
  };
  updateBridges = async ({
    add,
    remove
  }: {
    add?: AssetInfo[][][];
    remove?: AssetInfo[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_bridges: {
        add,
        remove
      }
    }, fee_, memo_, funds_);
  };
  swapBridgeAssets = async ({
    assets,
    depth
  }: {
    assets: AssetInfo[];
    depth: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      swap_bridge_assets: {
        assets,
        depth
      }
    }, fee_, memo_, funds_);
  };
  distributeAstro = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      distribute_astro: {}
    }, fee_, memo_, funds_);
  };
  proposeNewOwner = async ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      propose_new_owner: {
        expires_in: expiresIn,
        owner
      }
    }, fee_, memo_, funds_);
  };
  dropOwnershipProposal = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      drop_ownership_proposal: {}
    }, fee_, memo_, funds_);
  };
  claimOwnership = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_ownership: {}
    }, fee_, memo_, funds_);
  };
  enableRewards = async ({
    blocks
  }: {
    blocks: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      enable_rewards: {
        blocks
      }
    }, fee_, memo_, funds_);
  };
  seize = async ({
    assets
  }: {
    assets: AssetWithLimit[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      seize: {
        assets
      }
    }, fee_, memo_, funds_);
  };
  updateSeizeConfig = async ({
    receiver,
    seizableAssets
  }: {
    receiver?: string;
    seizableAssets?: AssetInfo[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_seize_config: {
        receiver,
        seizable_assets: seizableAssets
      }
    }, fee_, memo_, funds_);
  };
}