/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, Binary, PairType, InstantiateMsg, ExecuteMsg, Uint128, Decimal, Cw20ReceiveMsg, Asset, Empty, QueryMsg, Uint64, MigrateMsg, NullableUint128, Decimal256, ConfigResponse, CumulativePricesResponse, OracleObservation, PairInfo, PoolResponse, ReverseSimulationResponse, ArrayOfAsset, SimulationResponse } from "./AstroportPairConcentrated.types";
import { AstroportPairConcentratedQueryClient, AstroportPairConcentratedClient } from "./AstroportPairConcentrated.client";
export const astroportPairConcentratedQueryKeys = {
  contract: ([{
    contract: "astroportPairConcentrated"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportPairConcentratedQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  pair: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "pair",
    args
  }] as const),
  pool: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "pool",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  share: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "share",
    args
  }] as const),
  simulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "simulation",
    args
  }] as const),
  reverseSimulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "reverse_simulation",
    args
  }] as const),
  cumulativePrices: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "cumulative_prices",
    args
  }] as const),
  computeD: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "compute_d",
    args
  }] as const),
  lpPrice: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "lp_price",
    args
  }] as const),
  assetBalanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "asset_balance_at",
    args
  }] as const),
  observe: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "observe",
    args
  }] as const),
  simulateProvide: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "simulate_provide",
    args
  }] as const),
  simulateWithdraw: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedQueryKeys.address(contractAddress)[0],
    method: "simulate_withdraw",
    args
  }] as const)
};
export const astroportPairConcentratedQueries = {
  pair: <TData = PairInfo,>({
    client,
    options
  }: AstroportPairConcentratedPairQuery<TData>): UseQueryOptions<PairInfo, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.pair(client?.contractAddress),
    queryFn: () => client ? client.pair() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pool: <TData = PoolResponse,>({
    client,
    options
  }: AstroportPairConcentratedPoolQuery<TData>): UseQueryOptions<PoolResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.pool(client?.contractAddress),
    queryFn: () => client ? client.pool() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportPairConcentratedConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  share: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairConcentratedShareQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.share(client?.contractAddress, args),
    queryFn: () => client ? client.share({
      amount: args.amount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulation: <TData = SimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSimulationQuery<TData>): UseQueryOptions<SimulationResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.simulation(client?.contractAddress, args),
    queryFn: () => client ? client.simulation({
      askAssetInfo: args.askAssetInfo,
      offerAsset: args.offerAsset
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseSimulation: <TData = ReverseSimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConcentratedReverseSimulationQuery<TData>): UseQueryOptions<ReverseSimulationResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.reverseSimulation(client?.contractAddress, args),
    queryFn: () => client ? client.reverseSimulation({
      askAsset: args.askAsset,
      offerAssetInfo: args.offerAssetInfo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  cumulativePrices: <TData = CumulativePricesResponse,>({
    client,
    options
  }: AstroportPairConcentratedCumulativePricesQuery<TData>): UseQueryOptions<CumulativePricesResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.cumulativePrices(client?.contractAddress),
    queryFn: () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  computeD: <TData = Decimal256,>({
    client,
    options
  }: AstroportPairConcentratedComputeDQuery<TData>): UseQueryOptions<Decimal256, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.computeD(client?.contractAddress),
    queryFn: () => client ? client.computeD() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  lpPrice: <TData = Decimal256,>({
    client,
    options
  }: AstroportPairConcentratedLpPriceQuery<TData>): UseQueryOptions<Decimal256, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.lpPrice(client?.contractAddress),
    queryFn: () => client ? client.lpPrice() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  assetBalanceAt: <TData = NullableUint128,>({
    client,
    args,
    options
  }: AstroportPairConcentratedAssetBalanceAtQuery<TData>): UseQueryOptions<NullableUint128, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.assetBalanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.assetBalanceAt({
      assetInfo: args.assetInfo,
      blockHeight: args.blockHeight
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  observe: <TData = OracleObservation,>({
    client,
    args,
    options
  }: AstroportPairConcentratedObserveQuery<TData>): UseQueryOptions<OracleObservation, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.observe(client?.contractAddress, args),
    queryFn: () => client ? client.observe({
      secondsAgo: args.secondsAgo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateProvide: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSimulateProvideQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.simulateProvide(client?.contractAddress, args),
    queryFn: () => client ? client.simulateProvide({
      assets: args.assets,
      slippageTolerance: args.slippageTolerance
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateWithdraw: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSimulateWithdrawQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairConcentratedQueryKeys.simulateWithdraw(client?.contractAddress, args),
    queryFn: () => client ? client.simulateWithdraw({
      lpAmount: args.lpAmount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportPairConcentratedReactQuery<TResponse, TData = TResponse> {
  client: AstroportPairConcentratedQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportPairConcentratedSimulateWithdrawQuery<TData> extends AstroportPairConcentratedReactQuery<ArrayOfAsset, TData> {
  args: {
    lpAmount: Uint128;
  };
}
export function useAstroportPairConcentratedSimulateWithdrawQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairConcentratedSimulateWithdrawQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairConcentratedQueryKeys.simulateWithdraw(client?.contractAddress, args), () => client ? client.simulateWithdraw({
    lpAmount: args.lpAmount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSimulateProvideQuery<TData> extends AstroportPairConcentratedReactQuery<Uint128, TData> {
  args: {
    assets: Asset[];
    slippageTolerance?: Decimal;
  };
}
export function useAstroportPairConcentratedSimulateProvideQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportPairConcentratedSimulateProvideQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairConcentratedQueryKeys.simulateProvide(client?.contractAddress, args), () => client ? client.simulateProvide({
    assets: args.assets,
    slippageTolerance: args.slippageTolerance
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedObserveQuery<TData> extends AstroportPairConcentratedReactQuery<OracleObservation, TData> {
  args: {
    secondsAgo: number;
  };
}
export function useAstroportPairConcentratedObserveQuery<TData = OracleObservation>({
  client,
  args,
  options
}: AstroportPairConcentratedObserveQuery<TData>) {
  return useQuery<OracleObservation, Error, TData>(astroportPairConcentratedQueryKeys.observe(client?.contractAddress, args), () => client ? client.observe({
    secondsAgo: args.secondsAgo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedAssetBalanceAtQuery<TData> extends AstroportPairConcentratedReactQuery<NullableUint128, TData> {
  args: {
    assetInfo: AssetInfo;
    blockHeight: Uint64;
  };
}
export function useAstroportPairConcentratedAssetBalanceAtQuery<TData = NullableUint128>({
  client,
  args,
  options
}: AstroportPairConcentratedAssetBalanceAtQuery<TData>) {
  return useQuery<NullableUint128, Error, TData>(astroportPairConcentratedQueryKeys.assetBalanceAt(client?.contractAddress, args), () => client ? client.assetBalanceAt({
    assetInfo: args.assetInfo,
    blockHeight: args.blockHeight
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedLpPriceQuery<TData> extends AstroportPairConcentratedReactQuery<Decimal256, TData> {}
export function useAstroportPairConcentratedLpPriceQuery<TData = Decimal256>({
  client,
  options
}: AstroportPairConcentratedLpPriceQuery<TData>) {
  return useQuery<Decimal256, Error, TData>(astroportPairConcentratedQueryKeys.lpPrice(client?.contractAddress), () => client ? client.lpPrice() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedComputeDQuery<TData> extends AstroportPairConcentratedReactQuery<Decimal256, TData> {}
export function useAstroportPairConcentratedComputeDQuery<TData = Decimal256>({
  client,
  options
}: AstroportPairConcentratedComputeDQuery<TData>) {
  return useQuery<Decimal256, Error, TData>(astroportPairConcentratedQueryKeys.computeD(client?.contractAddress), () => client ? client.computeD() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedCumulativePricesQuery<TData> extends AstroportPairConcentratedReactQuery<CumulativePricesResponse, TData> {}
export function useAstroportPairConcentratedCumulativePricesQuery<TData = CumulativePricesResponse>({
  client,
  options
}: AstroportPairConcentratedCumulativePricesQuery<TData>) {
  return useQuery<CumulativePricesResponse, Error, TData>(astroportPairConcentratedQueryKeys.cumulativePrices(client?.contractAddress), () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedReverseSimulationQuery<TData> extends AstroportPairConcentratedReactQuery<ReverseSimulationResponse, TData> {
  args: {
    askAsset: Asset;
    offerAssetInfo?: AssetInfo;
  };
}
export function useAstroportPairConcentratedReverseSimulationQuery<TData = ReverseSimulationResponse>({
  client,
  args,
  options
}: AstroportPairConcentratedReverseSimulationQuery<TData>) {
  return useQuery<ReverseSimulationResponse, Error, TData>(astroportPairConcentratedQueryKeys.reverseSimulation(client?.contractAddress, args), () => client ? client.reverseSimulation({
    askAsset: args.askAsset,
    offerAssetInfo: args.offerAssetInfo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSimulationQuery<TData> extends AstroportPairConcentratedReactQuery<SimulationResponse, TData> {
  args: {
    askAssetInfo?: AssetInfo;
    offerAsset: Asset;
  };
}
export function useAstroportPairConcentratedSimulationQuery<TData = SimulationResponse>({
  client,
  args,
  options
}: AstroportPairConcentratedSimulationQuery<TData>) {
  return useQuery<SimulationResponse, Error, TData>(astroportPairConcentratedQueryKeys.simulation(client?.contractAddress, args), () => client ? client.simulation({
    askAssetInfo: args.askAssetInfo,
    offerAsset: args.offerAsset
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedShareQuery<TData> extends AstroportPairConcentratedReactQuery<ArrayOfAsset, TData> {
  args: {
    amount: Uint128;
  };
}
export function useAstroportPairConcentratedShareQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairConcentratedShareQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairConcentratedQueryKeys.share(client?.contractAddress, args), () => client ? client.share({
    amount: args.amount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedConfigQuery<TData> extends AstroportPairConcentratedReactQuery<ConfigResponse, TData> {}
export function useAstroportPairConcentratedConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportPairConcentratedConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportPairConcentratedQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedPoolQuery<TData> extends AstroportPairConcentratedReactQuery<PoolResponse, TData> {}
export function useAstroportPairConcentratedPoolQuery<TData = PoolResponse>({
  client,
  options
}: AstroportPairConcentratedPoolQuery<TData>) {
  return useQuery<PoolResponse, Error, TData>(astroportPairConcentratedQueryKeys.pool(client?.contractAddress), () => client ? client.pool() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedPairQuery<TData> extends AstroportPairConcentratedReactQuery<PairInfo, TData> {}
export function useAstroportPairConcentratedPairQuery<TData = PairInfo>({
  client,
  options
}: AstroportPairConcentratedPairQuery<TData>) {
  return useQuery<PairInfo, Error, TData>(astroportPairConcentratedQueryKeys.pair(client?.contractAddress), () => client ? client.pair() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedCustomMutation {
  client: AstroportPairConcentratedClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedCustomMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedCustomMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedCustomMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.custom(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedClaimOwnershipMutation {
  client: AstroportPairConcentratedClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportPairConcentratedDropOwnershipProposalMutation {
  client: AstroportPairConcentratedClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportPairConcentratedProposeNewOwnerMutation {
  client: AstroportPairConcentratedClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedUpdateConfigMutation {
  client: AstroportPairConcentratedClient;
  msg: {
    params: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedSwapMutation {
  client: AstroportPairConcentratedClient;
  msg: {
    askAssetInfo?: AssetInfo;
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSwapMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSwapMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSwapMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.swap(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedWithdrawLiquidityMutation {
  client: AstroportPairConcentratedClient;
  msg: {
    assets?: Asset[];
    minAssetsToReceive?: Asset[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedWithdrawLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedWithdrawLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedWithdrawLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.withdrawLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedProvideLiquidityMutation {
  client: AstroportPairConcentratedClient;
  msg: {
    assets: Asset[];
    autoStake?: boolean;
    minLpToReceive?: Uint128;
    receiver?: string;
    slippageTolerance?: Decimal;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedProvideLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedProvideLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedProvideLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.provideLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedReceiveMutation {
  client: AstroportPairConcentratedClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}