/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, Uint64, Decimal, InstantiateMsg, SecondReceiverParams, ExecuteMsg, Uint128, UpdateAddr, AssetWithLimit, UpdateDevFundConfig, DevFundConfig, QueryMsg, MigrateMsg, BalancesResponse, Asset, ArrayOfTupleOfStringAndString, ConfigResponse, SecondReceiverConfig, SeizeConfig } from "./AstroportMaker.types";
import { AstroportMakerQueryClient, AstroportMakerClient } from "./AstroportMaker.client";
export const astroportMakerQueryKeys = {
  contract: ([{
    contract: "astroportMaker"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportMakerQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportMakerQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  balances: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportMakerQueryKeys.address(contractAddress)[0],
    method: "balances",
    args
  }] as const),
  bridges: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportMakerQueryKeys.address(contractAddress)[0],
    method: "bridges",
    args
  }] as const),
  querySeizeConfig: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportMakerQueryKeys.address(contractAddress)[0],
    method: "query_seize_config",
    args
  }] as const)
};
export const astroportMakerQueries = {
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportMakerConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportMakerQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  balances: <TData = BalancesResponse,>({
    client,
    args,
    options
  }: AstroportMakerBalancesQuery<TData>): UseQueryOptions<BalancesResponse, Error, TData> => ({
    queryKey: astroportMakerQueryKeys.balances(client?.contractAddress, args),
    queryFn: () => client ? client.balances({
      assets: args.assets
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  bridges: <TData = ArrayOfTupleOfStringAndString,>({
    client,
    options
  }: AstroportMakerBridgesQuery<TData>): UseQueryOptions<ArrayOfTupleOfStringAndString, Error, TData> => ({
    queryKey: astroportMakerQueryKeys.bridges(client?.contractAddress),
    queryFn: () => client ? client.bridges() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  querySeizeConfig: <TData = SeizeConfig,>({
    client,
    options
  }: AstroportMakerQuerySeizeConfigQuery<TData>): UseQueryOptions<SeizeConfig, Error, TData> => ({
    queryKey: astroportMakerQueryKeys.querySeizeConfig(client?.contractAddress),
    queryFn: () => client ? client.querySeizeConfig() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportMakerReactQuery<TResponse, TData = TResponse> {
  client: AstroportMakerQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportMakerQuerySeizeConfigQuery<TData> extends AstroportMakerReactQuery<SeizeConfig, TData> {}
export function useAstroportMakerQuerySeizeConfigQuery<TData = SeizeConfig>({
  client,
  options
}: AstroportMakerQuerySeizeConfigQuery<TData>) {
  return useQuery<SeizeConfig, Error, TData>(astroportMakerQueryKeys.querySeizeConfig(client?.contractAddress), () => client ? client.querySeizeConfig() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportMakerBridgesQuery<TData> extends AstroportMakerReactQuery<ArrayOfTupleOfStringAndString, TData> {}
export function useAstroportMakerBridgesQuery<TData = ArrayOfTupleOfStringAndString>({
  client,
  options
}: AstroportMakerBridgesQuery<TData>) {
  return useQuery<ArrayOfTupleOfStringAndString, Error, TData>(astroportMakerQueryKeys.bridges(client?.contractAddress), () => client ? client.bridges() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportMakerBalancesQuery<TData> extends AstroportMakerReactQuery<BalancesResponse, TData> {
  args: {
    assets: AssetInfo[];
  };
}
export function useAstroportMakerBalancesQuery<TData = BalancesResponse>({
  client,
  args,
  options
}: AstroportMakerBalancesQuery<TData>) {
  return useQuery<BalancesResponse, Error, TData>(astroportMakerQueryKeys.balances(client?.contractAddress, args), () => client ? client.balances({
    assets: args.assets
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportMakerConfigQuery<TData> extends AstroportMakerReactQuery<ConfigResponse, TData> {}
export function useAstroportMakerConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportMakerConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportMakerQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportMakerUpdateSeizeConfigMutation {
  client: AstroportMakerClient;
  msg: {
    receiver?: string;
    seizableAssets?: AssetInfo[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerUpdateSeizeConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerUpdateSeizeConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerUpdateSeizeConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateSeizeConfig(msg, fee, memo, funds), options);
}
export interface AstroportMakerSeizeMutation {
  client: AstroportMakerClient;
  msg: {
    assets: AssetWithLimit[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerSeizeMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerSeizeMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerSeizeMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.seize(msg, fee, memo, funds), options);
}
export interface AstroportMakerEnableRewardsMutation {
  client: AstroportMakerClient;
  msg: {
    blocks: number;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerEnableRewardsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerEnableRewardsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerEnableRewardsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.enableRewards(msg, fee, memo, funds), options);
}
export interface AstroportMakerClaimOwnershipMutation {
  client: AstroportMakerClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportMakerDropOwnershipProposalMutation {
  client: AstroportMakerClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportMakerProposeNewOwnerMutation {
  client: AstroportMakerClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportMakerDistributeAstroMutation {
  client: AstroportMakerClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerDistributeAstroMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerDistributeAstroMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerDistributeAstroMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.distributeAstro(fee, memo, funds), options);
}
export interface AstroportMakerSwapBridgeAssetsMutation {
  client: AstroportMakerClient;
  msg: {
    assets: AssetInfo[];
    depth: number;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerSwapBridgeAssetsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerSwapBridgeAssetsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerSwapBridgeAssetsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.swapBridgeAssets(msg, fee, memo, funds), options);
}
export interface AstroportMakerUpdateBridgesMutation {
  client: AstroportMakerClient;
  msg: {
    add?: AssetInfo[][][];
    remove?: AssetInfo[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerUpdateBridgesMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerUpdateBridgesMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerUpdateBridgesMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateBridges(msg, fee, memo, funds), options);
}
export interface AstroportMakerUpdateConfigMutation {
  client: AstroportMakerClient;
  msg: {
    astroToken?: AssetInfo;
    basicAsset?: AssetInfo;
    collectCooldown?: number;
    devFundConfig?: UpdateDevFundConfig;
    factoryContract?: string;
    governanceContract?: UpdateAddr;
    governancePercent?: Uint64;
    maxSpread?: Decimal;
    secondReceiverParams?: SecondReceiverParams;
    stakingContract?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportMakerCollectMutation {
  client: AstroportMakerClient;
  msg: {
    assets: AssetWithLimit[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportMakerCollectMutation(options?: Omit<UseMutationOptions<any, Error, AstroportMakerCollectMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportMakerCollectMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.collect(msg, fee, memo, funds), options);
}