/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AssetInfo = {
  token: {
    contract_addr: Addr;
  };
} | {
  native_token: {
    denom: string;
  };
};
export type Addr = string;
export interface InstantiateMsg {
  owner: string;
  vesting_token: AssetInfo;
}
export type ExecuteMsg = {
  claim: {
    amount?: Uint128 | null;
    recipient?: string | null;
  };
} | {
  receive: Cw20ReceiveMsg;
} | {
  register_vesting_accounts: {
    vesting_accounts: VestingAccount[];
  };
} | {
  withdraw_from_active_schedule: {
    account: string;
    recipient?: string | null;
    withdraw_amount: Uint128;
  };
} | {
  propose_new_owner: {
    expires_in: number;
    owner: string;
  };
} | {
  drop_ownership_proposal: {};
} | {
  claim_ownership: {};
};
export type Uint128 = string;
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface VestingAccount {
  address: string;
  schedules: VestingSchedule[];
}
export interface VestingSchedule {
  end_point?: VestingSchedulePoint | null;
  start_point: VestingSchedulePoint;
}
export interface VestingSchedulePoint {
  amount: Uint128;
  time: number;
}
export type QueryMsg = {
  config: {};
} | {
  vesting_account: {
    address: string;
  };
} | {
  vesting_accounts: {
    limit?: number | null;
    order_by?: OrderBy | null;
    start_after?: string | null;
  };
} | {
  available_amount: {
    address: string;
  };
} | {
  timestamp: {};
};
export type OrderBy = "asc" | "desc";
export interface MigrateMsg {
  converter_contract: string;
}
export interface ConfigResponse {
  owner: Addr;
  vesting_token: AssetInfo;
}
export type Uint64 = number;
export interface VestingAccountResponse {
  address: Addr;
  info: VestingInfo;
}
export interface VestingInfo {
  released_amount: Uint128;
  schedules: VestingSchedule[];
}
export interface VestingAccountsResponse {
  vesting_accounts: VestingAccountResponse[];
}