/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, InstantiateMsg, ExecuteMsg, QueryMsg, Uint128, MigrateMsg, Uint256, ArrayOfTupleOfAssetInfoAndUint256 } from "./AstroportOracle.types";
import { AstroportOracleQueryClient, AstroportOracleClient } from "./AstroportOracle.client";
export const astroportOracleQueryKeys = {
  contract: ([{
    contract: "astroportOracle"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportOracleQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  consult: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportOracleQueryKeys.address(contractAddress)[0],
    method: "consult",
    args
  }] as const)
};
export const astroportOracleQueries = {
  consult: <TData = ArrayOfTupleOfAssetInfoAndUint256,>({
    client,
    args,
    options
  }: AstroportOracleConsultQuery<TData>): UseQueryOptions<ArrayOfTupleOfAssetInfoAndUint256, Error, TData> => ({
    queryKey: astroportOracleQueryKeys.consult(client?.contractAddress, args),
    queryFn: () => client ? client.consult({
      amount: args.amount,
      token: args.token
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportOracleReactQuery<TResponse, TData = TResponse> {
  client: AstroportOracleQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportOracleConsultQuery<TData> extends AstroportOracleReactQuery<ArrayOfTupleOfAssetInfoAndUint256, TData> {
  args: {
    amount: Uint128;
    token: AssetInfo;
  };
}
export function useAstroportOracleConsultQuery<TData = ArrayOfTupleOfAssetInfoAndUint256>({
  client,
  args,
  options
}: AstroportOracleConsultQuery<TData>) {
  return useQuery<ArrayOfTupleOfAssetInfoAndUint256, Error, TData>(astroportOracleQueryKeys.consult(client?.contractAddress, args), () => client ? client.consult({
    amount: args.amount,
    token: args.token
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportOracleUpdateMutation {
  client: AstroportOracleClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportOracleUpdateMutation(options?: Omit<UseMutationOptions<any, Error, AstroportOracleUpdateMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportOracleUpdateMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.update(fee, memo, funds), options);
}