/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Uint128, Binary, Decimal, SwapOperation, AssetInfo, Addr, Cw20ReceiveMsg, QueryMsg, ConfigResponse, SimulateSwapOperationsResponse } from "./AstroportRouter.types";
export interface AstroportRouterReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  simulateSwapOperations: ({
    offerAmount,
    operations
  }: {
    offerAmount: Uint128;
    operations: SwapOperation[];
  }) => Promise<SimulateSwapOperationsResponse>;
  reverseSimulateSwapOperations: ({
    askAmount,
    operations
  }: {
    askAmount: Uint128;
    operations: SwapOperation[];
  }) => Promise<Uint128>;
}
export class AstroportRouterQueryClient implements AstroportRouterReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.simulateSwapOperations = this.simulateSwapOperations.bind(this);
    this.reverseSimulateSwapOperations = this.reverseSimulateSwapOperations.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  simulateSwapOperations = async ({
    offerAmount,
    operations
  }: {
    offerAmount: Uint128;
    operations: SwapOperation[];
  }): Promise<SimulateSwapOperationsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      simulate_swap_operations: {
        offer_amount: offerAmount,
        operations
      }
    });
  };
  reverseSimulateSwapOperations = async ({
    askAmount,
    operations
  }: {
    askAmount: Uint128;
    operations: SwapOperation[];
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reverse_simulate_swap_operations: {
        ask_amount: askAmount,
        operations
      }
    });
  };
}
export interface AstroportRouterInterface {
  contractAddress: string;
  sender: string;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  executeSwapOperations: ({
    maxSpread,
    minimumReceive,
    operations,
    to
  }: {
    maxSpread?: Decimal;
    minimumReceive?: Uint128;
    operations: SwapOperation[];
    to?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  executeSwapOperation: ({
    maxSpread,
    operation,
    single,
    to
  }: {
    maxSpread?: Decimal;
    operation: SwapOperation;
    single: boolean;
    to?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroportRouterClient implements AstroportRouterInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.receive = this.receive.bind(this);
    this.executeSwapOperations = this.executeSwapOperations.bind(this);
    this.executeSwapOperation = this.executeSwapOperation.bind(this);
  }
  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee_, memo_, funds_);
  };
  executeSwapOperations = async ({
    maxSpread,
    minimumReceive,
    operations,
    to
  }: {
    maxSpread?: Decimal;
    minimumReceive?: Uint128;
    operations: SwapOperation[];
    to?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      execute_swap_operations: {
        max_spread: maxSpread,
        minimum_receive: minimumReceive,
        operations,
        to
      }
    }, fee_, memo_, funds_);
  };
  executeSwapOperation = async ({
    maxSpread,
    operation,
    single,
    to
  }: {
    maxSpread?: Decimal;
    operation: SwapOperation;
    single: boolean;
    to?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      execute_swap_operation: {
        max_spread: maxSpread,
        operation,
        single,
        to
      }
    }, fee_, memo_, funds_);
  };
}