/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, Binary, InstantiateMsg, ExecuteMsg, Uint128, Decimal, Cw20ReceiveMsg, Asset, QueryMsg, Uint64, MigrateMsg, NullableUint128, ConfigResponse, CumulativePricesResponse, OracleObservation, PairType, PairInfo, PoolResponse, ReverseSimulationResponse, ArrayOfAsset, SimulationResponse } from "./AstroportPairConverter.types";
import { AstroportPairConverterQueryClient, AstroportPairConverterClient } from "./AstroportPairConverter.client";
export const astroportPairConverterQueryKeys = {
  contract: ([{
    contract: "astroportPairConverter"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportPairConverterQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  pair: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "pair",
    args
  }] as const),
  pool: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "pool",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  share: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "share",
    args
  }] as const),
  simulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "simulation",
    args
  }] as const),
  reverseSimulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "reverse_simulation",
    args
  }] as const),
  cumulativePrices: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "cumulative_prices",
    args
  }] as const),
  queryComputeD: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "query_compute_d",
    args
  }] as const),
  assetBalanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "asset_balance_at",
    args
  }] as const),
  observe: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConverterQueryKeys.address(contractAddress)[0],
    method: "observe",
    args
  }] as const)
};
export const astroportPairConverterQueries = {
  pair: <TData = PairInfo,>({
    client,
    options
  }: AstroportPairConverterPairQuery<TData>): UseQueryOptions<PairInfo, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.pair(client?.contractAddress),
    queryFn: () => client ? client.pair() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pool: <TData = PoolResponse,>({
    client,
    options
  }: AstroportPairConverterPoolQuery<TData>): UseQueryOptions<PoolResponse, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.pool(client?.contractAddress),
    queryFn: () => client ? client.pool() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportPairConverterConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  share: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairConverterShareQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.share(client?.contractAddress, args),
    queryFn: () => client ? client.share({
      amount: args.amount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulation: <TData = SimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConverterSimulationQuery<TData>): UseQueryOptions<SimulationResponse, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.simulation(client?.contractAddress, args),
    queryFn: () => client ? client.simulation({
      askAssetInfo: args.askAssetInfo,
      offerAsset: args.offerAsset
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseSimulation: <TData = ReverseSimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConverterReverseSimulationQuery<TData>): UseQueryOptions<ReverseSimulationResponse, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.reverseSimulation(client?.contractAddress, args),
    queryFn: () => client ? client.reverseSimulation({
      askAsset: args.askAsset,
      offerAssetInfo: args.offerAssetInfo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  cumulativePrices: <TData = CumulativePricesResponse,>({
    client,
    options
  }: AstroportPairConverterCumulativePricesQuery<TData>): UseQueryOptions<CumulativePricesResponse, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.cumulativePrices(client?.contractAddress),
    queryFn: () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  queryComputeD: <TData = Uint128,>({
    client,
    options
  }: AstroportPairConverterQueryComputeDQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.queryComputeD(client?.contractAddress),
    queryFn: () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  assetBalanceAt: <TData = NullableUint128,>({
    client,
    args,
    options
  }: AstroportPairConverterAssetBalanceAtQuery<TData>): UseQueryOptions<NullableUint128, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.assetBalanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.assetBalanceAt({
      assetInfo: args.assetInfo,
      blockHeight: args.blockHeight
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  observe: <TData = OracleObservation,>({
    client,
    args,
    options
  }: AstroportPairConverterObserveQuery<TData>): UseQueryOptions<OracleObservation, Error, TData> => ({
    queryKey: astroportPairConverterQueryKeys.observe(client?.contractAddress, args),
    queryFn: () => client ? client.observe({
      secondsAgo: args.secondsAgo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportPairConverterReactQuery<TResponse, TData = TResponse> {
  client: AstroportPairConverterQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportPairConverterObserveQuery<TData> extends AstroportPairConverterReactQuery<OracleObservation, TData> {
  args: {
    secondsAgo: number;
  };
}
export function useAstroportPairConverterObserveQuery<TData = OracleObservation>({
  client,
  args,
  options
}: AstroportPairConverterObserveQuery<TData>) {
  return useQuery<OracleObservation, Error, TData>(astroportPairConverterQueryKeys.observe(client?.contractAddress, args), () => client ? client.observe({
    secondsAgo: args.secondsAgo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterAssetBalanceAtQuery<TData> extends AstroportPairConverterReactQuery<NullableUint128, TData> {
  args: {
    assetInfo: AssetInfo;
    blockHeight: Uint64;
  };
}
export function useAstroportPairConverterAssetBalanceAtQuery<TData = NullableUint128>({
  client,
  args,
  options
}: AstroportPairConverterAssetBalanceAtQuery<TData>) {
  return useQuery<NullableUint128, Error, TData>(astroportPairConverterQueryKeys.assetBalanceAt(client?.contractAddress, args), () => client ? client.assetBalanceAt({
    assetInfo: args.assetInfo,
    blockHeight: args.blockHeight
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterQueryComputeDQuery<TData> extends AstroportPairConverterReactQuery<Uint128, TData> {}
export function useAstroportPairConverterQueryComputeDQuery<TData = Uint128>({
  client,
  options
}: AstroportPairConverterQueryComputeDQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairConverterQueryKeys.queryComputeD(client?.contractAddress), () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterCumulativePricesQuery<TData> extends AstroportPairConverterReactQuery<CumulativePricesResponse, TData> {}
export function useAstroportPairConverterCumulativePricesQuery<TData = CumulativePricesResponse>({
  client,
  options
}: AstroportPairConverterCumulativePricesQuery<TData>) {
  return useQuery<CumulativePricesResponse, Error, TData>(astroportPairConverterQueryKeys.cumulativePrices(client?.contractAddress), () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterReverseSimulationQuery<TData> extends AstroportPairConverterReactQuery<ReverseSimulationResponse, TData> {
  args: {
    askAsset: Asset;
    offerAssetInfo?: AssetInfo;
  };
}
export function useAstroportPairConverterReverseSimulationQuery<TData = ReverseSimulationResponse>({
  client,
  args,
  options
}: AstroportPairConverterReverseSimulationQuery<TData>) {
  return useQuery<ReverseSimulationResponse, Error, TData>(astroportPairConverterQueryKeys.reverseSimulation(client?.contractAddress, args), () => client ? client.reverseSimulation({
    askAsset: args.askAsset,
    offerAssetInfo: args.offerAssetInfo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterSimulationQuery<TData> extends AstroportPairConverterReactQuery<SimulationResponse, TData> {
  args: {
    askAssetInfo?: AssetInfo;
    offerAsset: Asset;
  };
}
export function useAstroportPairConverterSimulationQuery<TData = SimulationResponse>({
  client,
  args,
  options
}: AstroportPairConverterSimulationQuery<TData>) {
  return useQuery<SimulationResponse, Error, TData>(astroportPairConverterQueryKeys.simulation(client?.contractAddress, args), () => client ? client.simulation({
    askAssetInfo: args.askAssetInfo,
    offerAsset: args.offerAsset
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterShareQuery<TData> extends AstroportPairConverterReactQuery<ArrayOfAsset, TData> {
  args: {
    amount: Uint128;
  };
}
export function useAstroportPairConverterShareQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairConverterShareQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairConverterQueryKeys.share(client?.contractAddress, args), () => client ? client.share({
    amount: args.amount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterConfigQuery<TData> extends AstroportPairConverterReactQuery<ConfigResponse, TData> {}
export function useAstroportPairConverterConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportPairConverterConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportPairConverterQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterPoolQuery<TData> extends AstroportPairConverterReactQuery<PoolResponse, TData> {}
export function useAstroportPairConverterPoolQuery<TData = PoolResponse>({
  client,
  options
}: AstroportPairConverterPoolQuery<TData>) {
  return useQuery<PoolResponse, Error, TData>(astroportPairConverterQueryKeys.pool(client?.contractAddress), () => client ? client.pool() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterPairQuery<TData> extends AstroportPairConverterReactQuery<PairInfo, TData> {}
export function useAstroportPairConverterPairQuery<TData = PairInfo>({
  client,
  options
}: AstroportPairConverterPairQuery<TData>) {
  return useQuery<PairInfo, Error, TData>(astroportPairConverterQueryKeys.pair(client?.contractAddress), () => client ? client.pair() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConverterClaimOwnershipMutation {
  client: AstroportPairConverterClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConverterClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConverterClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConverterClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportPairConverterDropOwnershipProposalMutation {
  client: AstroportPairConverterClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConverterDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConverterDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConverterDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportPairConverterProposeNewOwnerMutation {
  client: AstroportPairConverterClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConverterProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConverterProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConverterProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportPairConverterUpdateConfigMutation {
  client: AstroportPairConverterClient;
  msg: {
    params: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConverterUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConverterUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConverterUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportPairConverterSwapMutation {
  client: AstroportPairConverterClient;
  msg: {
    askAssetInfo?: AssetInfo;
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConverterSwapMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConverterSwapMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConverterSwapMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.swap(msg, fee, memo, funds), options);
}
export interface AstroportPairConverterProvideLiquidityMutation {
  client: AstroportPairConverterClient;
  msg: {
    assets: Asset[];
    autoStake?: boolean;
    receiver?: string;
    slippageTolerance?: Decimal;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConverterProvideLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConverterProvideLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConverterProvideLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.provideLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairConverterReceiveMutation {
  client: AstroportPairConverterClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConverterReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConverterReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConverterReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}