/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, Binary, PairType, InstantiateMsg, ExecuteMsg, Uint128, Decimal, Cw20ReceiveMsg, Asset, Empty, QueryMsg, Uint64, MigrateMsg, NullableUint128, ConfigResponse, CumulativePricesResponse, OracleObservation, PairInfo, PoolResponse, ReverseSimulationResponse, ArrayOfAsset, SimulationResponse } from "./AstroportPair.types";
import { AstroportPairQueryClient, AstroportPairClient } from "./AstroportPair.client";
export const astroportPairQueryKeys = {
  contract: ([{
    contract: "astroportPair"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportPairQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  pair: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "pair",
    args
  }] as const),
  pool: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "pool",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  share: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "share",
    args
  }] as const),
  simulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "simulation",
    args
  }] as const),
  reverseSimulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "reverse_simulation",
    args
  }] as const),
  cumulativePrices: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "cumulative_prices",
    args
  }] as const),
  queryComputeD: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "query_compute_d",
    args
  }] as const),
  assetBalanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "asset_balance_at",
    args
  }] as const),
  observe: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "observe",
    args
  }] as const),
  simulateWithdraw: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "simulate_withdraw",
    args
  }] as const),
  simulateProvide: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairQueryKeys.address(contractAddress)[0],
    method: "simulate_provide",
    args
  }] as const)
};
export const astroportPairQueries = {
  pair: <TData = PairInfo,>({
    client,
    options
  }: AstroportPairPairQuery<TData>): UseQueryOptions<PairInfo, Error, TData> => ({
    queryKey: astroportPairQueryKeys.pair(client?.contractAddress),
    queryFn: () => client ? client.pair() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pool: <TData = PoolResponse,>({
    client,
    options
  }: AstroportPairPoolQuery<TData>): UseQueryOptions<PoolResponse, Error, TData> => ({
    queryKey: astroportPairQueryKeys.pool(client?.contractAddress),
    queryFn: () => client ? client.pool() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportPairConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportPairQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  share: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairShareQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairQueryKeys.share(client?.contractAddress, args),
    queryFn: () => client ? client.share({
      amount: args.amount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulation: <TData = SimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairSimulationQuery<TData>): UseQueryOptions<SimulationResponse, Error, TData> => ({
    queryKey: astroportPairQueryKeys.simulation(client?.contractAddress, args),
    queryFn: () => client ? client.simulation({
      askAssetInfo: args.askAssetInfo,
      offerAsset: args.offerAsset
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseSimulation: <TData = ReverseSimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairReverseSimulationQuery<TData>): UseQueryOptions<ReverseSimulationResponse, Error, TData> => ({
    queryKey: astroportPairQueryKeys.reverseSimulation(client?.contractAddress, args),
    queryFn: () => client ? client.reverseSimulation({
      askAsset: args.askAsset,
      offerAssetInfo: args.offerAssetInfo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  cumulativePrices: <TData = CumulativePricesResponse,>({
    client,
    options
  }: AstroportPairCumulativePricesQuery<TData>): UseQueryOptions<CumulativePricesResponse, Error, TData> => ({
    queryKey: astroportPairQueryKeys.cumulativePrices(client?.contractAddress),
    queryFn: () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  queryComputeD: <TData = Uint128,>({
    client,
    options
  }: AstroportPairQueryComputeDQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairQueryKeys.queryComputeD(client?.contractAddress),
    queryFn: () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  assetBalanceAt: <TData = NullableUint128,>({
    client,
    args,
    options
  }: AstroportPairAssetBalanceAtQuery<TData>): UseQueryOptions<NullableUint128, Error, TData> => ({
    queryKey: astroportPairQueryKeys.assetBalanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.assetBalanceAt({
      assetInfo: args.assetInfo,
      blockHeight: args.blockHeight
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  observe: <TData = OracleObservation,>({
    client,
    args,
    options
  }: AstroportPairObserveQuery<TData>): UseQueryOptions<OracleObservation, Error, TData> => ({
    queryKey: astroportPairQueryKeys.observe(client?.contractAddress, args),
    queryFn: () => client ? client.observe({
      secondsAgo: args.secondsAgo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateWithdraw: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairSimulateWithdrawQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairQueryKeys.simulateWithdraw(client?.contractAddress, args),
    queryFn: () => client ? client.simulateWithdraw({
      lpAmount: args.lpAmount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateProvide: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportPairSimulateProvideQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairQueryKeys.simulateProvide(client?.contractAddress, args),
    queryFn: () => client ? client.simulateProvide({
      assets: args.assets,
      slippageTolerance: args.slippageTolerance
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportPairReactQuery<TResponse, TData = TResponse> {
  client: AstroportPairQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportPairSimulateProvideQuery<TData> extends AstroportPairReactQuery<Uint128, TData> {
  args: {
    assets: Asset[];
    slippageTolerance?: Decimal;
  };
}
export function useAstroportPairSimulateProvideQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportPairSimulateProvideQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairQueryKeys.simulateProvide(client?.contractAddress, args), () => client ? client.simulateProvide({
    assets: args.assets,
    slippageTolerance: args.slippageTolerance
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairSimulateWithdrawQuery<TData> extends AstroportPairReactQuery<ArrayOfAsset, TData> {
  args: {
    lpAmount: Uint128;
  };
}
export function useAstroportPairSimulateWithdrawQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairSimulateWithdrawQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairQueryKeys.simulateWithdraw(client?.contractAddress, args), () => client ? client.simulateWithdraw({
    lpAmount: args.lpAmount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairObserveQuery<TData> extends AstroportPairReactQuery<OracleObservation, TData> {
  args: {
    secondsAgo: number;
  };
}
export function useAstroportPairObserveQuery<TData = OracleObservation>({
  client,
  args,
  options
}: AstroportPairObserveQuery<TData>) {
  return useQuery<OracleObservation, Error, TData>(astroportPairQueryKeys.observe(client?.contractAddress, args), () => client ? client.observe({
    secondsAgo: args.secondsAgo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairAssetBalanceAtQuery<TData> extends AstroportPairReactQuery<NullableUint128, TData> {
  args: {
    assetInfo: AssetInfo;
    blockHeight: Uint64;
  };
}
export function useAstroportPairAssetBalanceAtQuery<TData = NullableUint128>({
  client,
  args,
  options
}: AstroportPairAssetBalanceAtQuery<TData>) {
  return useQuery<NullableUint128, Error, TData>(astroportPairQueryKeys.assetBalanceAt(client?.contractAddress, args), () => client ? client.assetBalanceAt({
    assetInfo: args.assetInfo,
    blockHeight: args.blockHeight
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairQueryComputeDQuery<TData> extends AstroportPairReactQuery<Uint128, TData> {}
export function useAstroportPairQueryComputeDQuery<TData = Uint128>({
  client,
  options
}: AstroportPairQueryComputeDQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairQueryKeys.queryComputeD(client?.contractAddress), () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairCumulativePricesQuery<TData> extends AstroportPairReactQuery<CumulativePricesResponse, TData> {}
export function useAstroportPairCumulativePricesQuery<TData = CumulativePricesResponse>({
  client,
  options
}: AstroportPairCumulativePricesQuery<TData>) {
  return useQuery<CumulativePricesResponse, Error, TData>(astroportPairQueryKeys.cumulativePrices(client?.contractAddress), () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairReverseSimulationQuery<TData> extends AstroportPairReactQuery<ReverseSimulationResponse, TData> {
  args: {
    askAsset: Asset;
    offerAssetInfo?: AssetInfo;
  };
}
export function useAstroportPairReverseSimulationQuery<TData = ReverseSimulationResponse>({
  client,
  args,
  options
}: AstroportPairReverseSimulationQuery<TData>) {
  return useQuery<ReverseSimulationResponse, Error, TData>(astroportPairQueryKeys.reverseSimulation(client?.contractAddress, args), () => client ? client.reverseSimulation({
    askAsset: args.askAsset,
    offerAssetInfo: args.offerAssetInfo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairSimulationQuery<TData> extends AstroportPairReactQuery<SimulationResponse, TData> {
  args: {
    askAssetInfo?: AssetInfo;
    offerAsset: Asset;
  };
}
export function useAstroportPairSimulationQuery<TData = SimulationResponse>({
  client,
  args,
  options
}: AstroportPairSimulationQuery<TData>) {
  return useQuery<SimulationResponse, Error, TData>(astroportPairQueryKeys.simulation(client?.contractAddress, args), () => client ? client.simulation({
    askAssetInfo: args.askAssetInfo,
    offerAsset: args.offerAsset
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairShareQuery<TData> extends AstroportPairReactQuery<ArrayOfAsset, TData> {
  args: {
    amount: Uint128;
  };
}
export function useAstroportPairShareQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairShareQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairQueryKeys.share(client?.contractAddress, args), () => client ? client.share({
    amount: args.amount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConfigQuery<TData> extends AstroportPairReactQuery<ConfigResponse, TData> {}
export function useAstroportPairConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportPairConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportPairQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairPoolQuery<TData> extends AstroportPairReactQuery<PoolResponse, TData> {}
export function useAstroportPairPoolQuery<TData = PoolResponse>({
  client,
  options
}: AstroportPairPoolQuery<TData>) {
  return useQuery<PoolResponse, Error, TData>(astroportPairQueryKeys.pool(client?.contractAddress), () => client ? client.pool() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairPairQuery<TData> extends AstroportPairReactQuery<PairInfo, TData> {}
export function useAstroportPairPairQuery<TData = PairInfo>({
  client,
  options
}: AstroportPairPairQuery<TData>) {
  return useQuery<PairInfo, Error, TData>(astroportPairQueryKeys.pair(client?.contractAddress), () => client ? client.pair() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairCustomMutation {
  client: AstroportPairClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairCustomMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairCustomMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairCustomMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.custom(msg, fee, memo, funds), options);
}
export interface AstroportPairClaimOwnershipMutation {
  client: AstroportPairClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportPairDropOwnershipProposalMutation {
  client: AstroportPairClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportPairProposeNewOwnerMutation {
  client: AstroportPairClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportPairUpdateConfigMutation {
  client: AstroportPairClient;
  msg: {
    params: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportPairSwapMutation {
  client: AstroportPairClient;
  msg: {
    askAssetInfo?: AssetInfo;
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairSwapMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairSwapMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairSwapMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.swap(msg, fee, memo, funds), options);
}
export interface AstroportPairWithdrawLiquidityMutation {
  client: AstroportPairClient;
  msg: {
    assets?: Asset[];
    minAssetsToReceive?: Asset[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairWithdrawLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairWithdrawLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairWithdrawLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.withdrawLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairProvideLiquidityMutation {
  client: AstroportPairClient;
  msg: {
    assets: Asset[];
    autoStake?: boolean;
    minLpToReceive?: Uint128;
    receiver?: string;
    slippageTolerance?: Decimal;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairProvideLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairProvideLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairProvideLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.provideLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairReceiveMutation {
  client: AstroportPairClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}