/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AssetInfo = {
  token: {
    contract_addr: Addr;
  };
} | {
  native_token: {
    denom: string;
  };
};
export type Addr = string;
export type Uint64 = string;
export type Decimal = string;
export interface InstantiateMsg {
  astro_token: AssetInfo;
  collect_cooldown?: number | null;
  default_bridge?: AssetInfo | null;
  factory_contract: string;
  governance_contract?: string | null;
  governance_percent?: Uint64 | null;
  max_spread?: Decimal | null;
  owner: string;
  second_receiver_params?: SecondReceiverParams | null;
  staking_contract?: string | null;
}
export interface SecondReceiverParams {
  second_fee_receiver: string;
  second_receiver_cut: Uint64;
}
export type ExecuteMsg = {
  collect: {
    assets: AssetWithLimit[];
  };
} | {
  update_config: {
    astro_token?: AssetInfo | null;
    basic_asset?: AssetInfo | null;
    collect_cooldown?: number | null;
    dev_fund_config?: UpdateDevFundConfig | null;
    factory_contract?: string | null;
    governance_contract?: UpdateAddr | null;
    governance_percent?: Uint64 | null;
    max_spread?: Decimal | null;
    second_receiver_params?: SecondReceiverParams | null;
    staking_contract?: string | null;
  };
} | {
  update_bridges: {
    add?: [AssetInfo, AssetInfo][] | null;
    remove?: AssetInfo[] | null;
  };
} | {
  swap_bridge_assets: {
    assets: AssetInfo[];
    depth: number;
  };
} | {
  distribute_astro: {};
} | {
  propose_new_owner: {
    expires_in: number;
    owner: string;
  };
} | {
  drop_ownership_proposal: {};
} | {
  claim_ownership: {};
} | {
  enable_rewards: {
    blocks: number;
  };
} | {
  seize: {
    assets: AssetWithLimit[];
  };
} | {
  update_seize_config: {
    receiver?: string | null;
    seizable_assets?: AssetInfo[];
  };
};
export type Uint128 = string;
export type UpdateAddr = {
  set: string;
} | {
  remove: {};
};
export interface AssetWithLimit {
  info: AssetInfo;
  limit?: Uint128 | null;
}
export interface UpdateDevFundConfig {
  set?: DevFundConfig | null;
}
export interface DevFundConfig {
  address: string;
  asset_info: AssetInfo;
  share: Decimal;
}
export type QueryMsg = {
  config: {};
} | {
  balances: {
    assets: AssetInfo[];
  };
} | {
  bridges: {};
} | {
  query_seize_config: {};
};
export interface MigrateMsg {
  collect_cooldown?: number | null;
  second_receiver_params?: SecondReceiverParams | null;
}
export interface BalancesResponse {
  balances: Asset[];
}
export interface Asset {
  amount: Uint128;
  info: AssetInfo;
}
export type ArrayOfTupleOfStringAndString = [string, string][];
export interface ConfigResponse {
  astro_token: AssetInfo;
  default_bridge?: AssetInfo | null;
  dev_fund_conf?: DevFundConfig | null;
  factory_contract: Addr;
  governance_contract?: Addr | null;
  governance_percent: Uint64;
  max_spread: Decimal;
  owner: Addr;
  pre_upgrade_astro_amount: Uint128;
  remainder_reward: Uint128;
  second_receiver_cfg?: SecondReceiverConfig | null;
  staking_contract?: Addr | null;
}
export interface SecondReceiverConfig {
  second_fee_receiver: Addr;
  second_receiver_cut: Uint64;
}
export interface SeizeConfig {
  receiver: Addr;
  seizable_assets: AssetInfo[];
}