/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { AssetInfo, Addr, InstantiateMsg, ExecuteMsg, Uint128, Binary, Cw20ReceiveMsg, VestingAccount, VestingSchedule, VestingSchedulePoint, QueryMsg, OrderBy, MigrateMsg, ConfigResponse, Uint64, VestingAccountResponse, VestingInfo, VestingAccountsResponse } from "./AstroportVesting.types";
export interface AstroportVestingReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  vestingAccount: ({
    address
  }: {
    address: string;
  }) => Promise<VestingAccountResponse>;
  vestingAccounts: ({
    limit,
    orderBy,
    startAfter
  }: {
    limit?: number;
    orderBy?: OrderBy;
    startAfter?: string;
  }) => Promise<VestingAccountsResponse>;
  availableAmount: ({
    address
  }: {
    address: string;
  }) => Promise<Uint128>;
  timestamp: () => Promise<Uint64>;
}
export class AstroportVestingQueryClient implements AstroportVestingReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.vestingAccount = this.vestingAccount.bind(this);
    this.vestingAccounts = this.vestingAccounts.bind(this);
    this.availableAmount = this.availableAmount.bind(this);
    this.timestamp = this.timestamp.bind(this);
  }
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  vestingAccount = async ({
    address
  }: {
    address: string;
  }): Promise<VestingAccountResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vesting_account: {
        address
      }
    });
  };
  vestingAccounts = async ({
    limit,
    orderBy,
    startAfter
  }: {
    limit?: number;
    orderBy?: OrderBy;
    startAfter?: string;
  }): Promise<VestingAccountsResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      vesting_accounts: {
        limit,
        order_by: orderBy,
        start_after: startAfter
      }
    });
  };
  availableAmount = async ({
    address
  }: {
    address: string;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      available_amount: {
        address
      }
    });
  };
  timestamp = async (): Promise<Uint64> => {
    return this.client.queryContractSmart(this.contractAddress, {
      timestamp: {}
    });
  };
}
export interface AstroportVestingInterface {
  contractAddress: string;
  sender: string;
  claim: ({
    amount,
    recipient
  }: {
    amount?: Uint128;
    recipient?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  registerVestingAccounts: ({
    vestingAccounts
  }: {
    vestingAccounts: VestingAccount[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  withdrawFromActiveSchedule: ({
    account,
    recipient,
    withdrawAmount
  }: {
    account: string;
    recipient?: string;
    withdrawAmount: Uint128;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  proposeNewOwner: ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  dropOwnershipProposal: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  claimOwnership: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroportVestingClient implements AstroportVestingInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.claim = this.claim.bind(this);
    this.receive = this.receive.bind(this);
    this.registerVestingAccounts = this.registerVestingAccounts.bind(this);
    this.withdrawFromActiveSchedule = this.withdrawFromActiveSchedule.bind(this);
    this.proposeNewOwner = this.proposeNewOwner.bind(this);
    this.dropOwnershipProposal = this.dropOwnershipProposal.bind(this);
    this.claimOwnership = this.claimOwnership.bind(this);
  }
  claim = async ({
    amount,
    recipient
  }: {
    amount?: Uint128;
    recipient?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {
        amount,
        recipient
      }
    }, fee_, memo_, funds_);
  };
  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee_, memo_, funds_);
  };
  registerVestingAccounts = async ({
    vestingAccounts
  }: {
    vestingAccounts: VestingAccount[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      register_vesting_accounts: {
        vesting_accounts: vestingAccounts
      }
    }, fee_, memo_, funds_);
  };
  withdrawFromActiveSchedule = async ({
    account,
    recipient,
    withdrawAmount
  }: {
    account: string;
    recipient?: string;
    withdrawAmount: Uint128;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw_from_active_schedule: {
        account,
        recipient,
        withdraw_amount: withdrawAmount
      }
    }, fee_, memo_, funds_);
  };
  proposeNewOwner = async ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      propose_new_owner: {
        expires_in: expiresIn,
        owner
      }
    }, fee_, memo_, funds_);
  };
  dropOwnershipProposal = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      drop_ownership_proposal: {}
    }, fee_, memo_, funds_);
  };
  claimOwnership = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_ownership: {}
    }, fee_, memo_, funds_);
  };
}