/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, Binary, PairType, InstantiateMsg, ExecuteMsg, Uint128, Decimal, Cw20ReceiveMsg, Asset, Empty, QueryMsg, Uint64, MigrateMsg, TaxConfigsForString, TaxConfigForString, NullableUint128, ConfigResponse, CumulativePricesResponse, OracleObservation, PairInfo, PoolResponse, ReverseSimulationResponse, ArrayOfAsset, SimulationResponse } from "./AstroportPairXykSaleTax.types";
import { AstroportPairXykSaleTaxQueryClient, AstroportPairXykSaleTaxClient } from "./AstroportPairXykSaleTax.client";
export const astroportPairXykSaleTaxQueryKeys = {
  contract: ([{
    contract: "astroportPairXykSaleTax"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportPairXykSaleTaxQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  pair: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "pair",
    args
  }] as const),
  pool: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "pool",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  share: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "share",
    args
  }] as const),
  simulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "simulation",
    args
  }] as const),
  reverseSimulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "reverse_simulation",
    args
  }] as const),
  cumulativePrices: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "cumulative_prices",
    args
  }] as const),
  queryComputeD: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "query_compute_d",
    args
  }] as const),
  assetBalanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "asset_balance_at",
    args
  }] as const),
  observe: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "observe",
    args
  }] as const),
  simulateWithdraw: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "simulate_withdraw",
    args
  }] as const),
  simulateProvide: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairXykSaleTaxQueryKeys.address(contractAddress)[0],
    method: "simulate_provide",
    args
  }] as const)
};
export const astroportPairXykSaleTaxQueries = {
  pair: <TData = PairInfo,>({
    client,
    options
  }: AstroportPairXykSaleTaxPairQuery<TData>): UseQueryOptions<PairInfo, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.pair(client?.contractAddress),
    queryFn: () => client ? client.pair() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pool: <TData = PoolResponse,>({
    client,
    options
  }: AstroportPairXykSaleTaxPoolQuery<TData>): UseQueryOptions<PoolResponse, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.pool(client?.contractAddress),
    queryFn: () => client ? client.pool() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportPairXykSaleTaxConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  share: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairXykSaleTaxShareQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.share(client?.contractAddress, args),
    queryFn: () => client ? client.share({
      amount: args.amount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulation: <TData = SimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairXykSaleTaxSimulationQuery<TData>): UseQueryOptions<SimulationResponse, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.simulation(client?.contractAddress, args),
    queryFn: () => client ? client.simulation({
      askAssetInfo: args.askAssetInfo,
      offerAsset: args.offerAsset
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseSimulation: <TData = ReverseSimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairXykSaleTaxReverseSimulationQuery<TData>): UseQueryOptions<ReverseSimulationResponse, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.reverseSimulation(client?.contractAddress, args),
    queryFn: () => client ? client.reverseSimulation({
      askAsset: args.askAsset,
      offerAssetInfo: args.offerAssetInfo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  cumulativePrices: <TData = CumulativePricesResponse,>({
    client,
    options
  }: AstroportPairXykSaleTaxCumulativePricesQuery<TData>): UseQueryOptions<CumulativePricesResponse, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.cumulativePrices(client?.contractAddress),
    queryFn: () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  queryComputeD: <TData = Uint128,>({
    client,
    options
  }: AstroportPairXykSaleTaxQueryComputeDQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.queryComputeD(client?.contractAddress),
    queryFn: () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  assetBalanceAt: <TData = NullableUint128,>({
    client,
    args,
    options
  }: AstroportPairXykSaleTaxAssetBalanceAtQuery<TData>): UseQueryOptions<NullableUint128, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.assetBalanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.assetBalanceAt({
      assetInfo: args.assetInfo,
      blockHeight: args.blockHeight
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  observe: <TData = OracleObservation,>({
    client,
    args,
    options
  }: AstroportPairXykSaleTaxObserveQuery<TData>): UseQueryOptions<OracleObservation, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.observe(client?.contractAddress, args),
    queryFn: () => client ? client.observe({
      secondsAgo: args.secondsAgo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateWithdraw: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairXykSaleTaxSimulateWithdrawQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.simulateWithdraw(client?.contractAddress, args),
    queryFn: () => client ? client.simulateWithdraw({
      lpAmount: args.lpAmount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateProvide: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportPairXykSaleTaxSimulateProvideQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairXykSaleTaxQueryKeys.simulateProvide(client?.contractAddress, args),
    queryFn: () => client ? client.simulateProvide({
      assets: args.assets,
      slippageTolerance: args.slippageTolerance
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportPairXykSaleTaxReactQuery<TResponse, TData = TResponse> {
  client: AstroportPairXykSaleTaxQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportPairXykSaleTaxSimulateProvideQuery<TData> extends AstroportPairXykSaleTaxReactQuery<Uint128, TData> {
  args: {
    assets: Asset[];
    slippageTolerance?: Decimal;
  };
}
export function useAstroportPairXykSaleTaxSimulateProvideQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportPairXykSaleTaxSimulateProvideQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairXykSaleTaxQueryKeys.simulateProvide(client?.contractAddress, args), () => client ? client.simulateProvide({
    assets: args.assets,
    slippageTolerance: args.slippageTolerance
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxSimulateWithdrawQuery<TData> extends AstroportPairXykSaleTaxReactQuery<ArrayOfAsset, TData> {
  args: {
    lpAmount: Uint128;
  };
}
export function useAstroportPairXykSaleTaxSimulateWithdrawQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairXykSaleTaxSimulateWithdrawQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairXykSaleTaxQueryKeys.simulateWithdraw(client?.contractAddress, args), () => client ? client.simulateWithdraw({
    lpAmount: args.lpAmount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxObserveQuery<TData> extends AstroportPairXykSaleTaxReactQuery<OracleObservation, TData> {
  args: {
    secondsAgo: number;
  };
}
export function useAstroportPairXykSaleTaxObserveQuery<TData = OracleObservation>({
  client,
  args,
  options
}: AstroportPairXykSaleTaxObserveQuery<TData>) {
  return useQuery<OracleObservation, Error, TData>(astroportPairXykSaleTaxQueryKeys.observe(client?.contractAddress, args), () => client ? client.observe({
    secondsAgo: args.secondsAgo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxAssetBalanceAtQuery<TData> extends AstroportPairXykSaleTaxReactQuery<NullableUint128, TData> {
  args: {
    assetInfo: AssetInfo;
    blockHeight: Uint64;
  };
}
export function useAstroportPairXykSaleTaxAssetBalanceAtQuery<TData = NullableUint128>({
  client,
  args,
  options
}: AstroportPairXykSaleTaxAssetBalanceAtQuery<TData>) {
  return useQuery<NullableUint128, Error, TData>(astroportPairXykSaleTaxQueryKeys.assetBalanceAt(client?.contractAddress, args), () => client ? client.assetBalanceAt({
    assetInfo: args.assetInfo,
    blockHeight: args.blockHeight
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxQueryComputeDQuery<TData> extends AstroportPairXykSaleTaxReactQuery<Uint128, TData> {}
export function useAstroportPairXykSaleTaxQueryComputeDQuery<TData = Uint128>({
  client,
  options
}: AstroportPairXykSaleTaxQueryComputeDQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairXykSaleTaxQueryKeys.queryComputeD(client?.contractAddress), () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxCumulativePricesQuery<TData> extends AstroportPairXykSaleTaxReactQuery<CumulativePricesResponse, TData> {}
export function useAstroportPairXykSaleTaxCumulativePricesQuery<TData = CumulativePricesResponse>({
  client,
  options
}: AstroportPairXykSaleTaxCumulativePricesQuery<TData>) {
  return useQuery<CumulativePricesResponse, Error, TData>(astroportPairXykSaleTaxQueryKeys.cumulativePrices(client?.contractAddress), () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxReverseSimulationQuery<TData> extends AstroportPairXykSaleTaxReactQuery<ReverseSimulationResponse, TData> {
  args: {
    askAsset: Asset;
    offerAssetInfo?: AssetInfo;
  };
}
export function useAstroportPairXykSaleTaxReverseSimulationQuery<TData = ReverseSimulationResponse>({
  client,
  args,
  options
}: AstroportPairXykSaleTaxReverseSimulationQuery<TData>) {
  return useQuery<ReverseSimulationResponse, Error, TData>(astroportPairXykSaleTaxQueryKeys.reverseSimulation(client?.contractAddress, args), () => client ? client.reverseSimulation({
    askAsset: args.askAsset,
    offerAssetInfo: args.offerAssetInfo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxSimulationQuery<TData> extends AstroportPairXykSaleTaxReactQuery<SimulationResponse, TData> {
  args: {
    askAssetInfo?: AssetInfo;
    offerAsset: Asset;
  };
}
export function useAstroportPairXykSaleTaxSimulationQuery<TData = SimulationResponse>({
  client,
  args,
  options
}: AstroportPairXykSaleTaxSimulationQuery<TData>) {
  return useQuery<SimulationResponse, Error, TData>(astroportPairXykSaleTaxQueryKeys.simulation(client?.contractAddress, args), () => client ? client.simulation({
    askAssetInfo: args.askAssetInfo,
    offerAsset: args.offerAsset
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxShareQuery<TData> extends AstroportPairXykSaleTaxReactQuery<ArrayOfAsset, TData> {
  args: {
    amount: Uint128;
  };
}
export function useAstroportPairXykSaleTaxShareQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairXykSaleTaxShareQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairXykSaleTaxQueryKeys.share(client?.contractAddress, args), () => client ? client.share({
    amount: args.amount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxConfigQuery<TData> extends AstroportPairXykSaleTaxReactQuery<ConfigResponse, TData> {}
export function useAstroportPairXykSaleTaxConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportPairXykSaleTaxConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportPairXykSaleTaxQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxPoolQuery<TData> extends AstroportPairXykSaleTaxReactQuery<PoolResponse, TData> {}
export function useAstroportPairXykSaleTaxPoolQuery<TData = PoolResponse>({
  client,
  options
}: AstroportPairXykSaleTaxPoolQuery<TData>) {
  return useQuery<PoolResponse, Error, TData>(astroportPairXykSaleTaxQueryKeys.pool(client?.contractAddress), () => client ? client.pool() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxPairQuery<TData> extends AstroportPairXykSaleTaxReactQuery<PairInfo, TData> {}
export function useAstroportPairXykSaleTaxPairQuery<TData = PairInfo>({
  client,
  options
}: AstroportPairXykSaleTaxPairQuery<TData>) {
  return useQuery<PairInfo, Error, TData>(astroportPairXykSaleTaxQueryKeys.pair(client?.contractAddress), () => client ? client.pair() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairXykSaleTaxCustomMutation {
  client: AstroportPairXykSaleTaxClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxCustomMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxCustomMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxCustomMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.custom(msg, fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxClaimOwnershipMutation {
  client: AstroportPairXykSaleTaxClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxDropOwnershipProposalMutation {
  client: AstroportPairXykSaleTaxClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxProposeNewOwnerMutation {
  client: AstroportPairXykSaleTaxClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxUpdateConfigMutation {
  client: AstroportPairXykSaleTaxClient;
  msg: {
    params: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxSwapMutation {
  client: AstroportPairXykSaleTaxClient;
  msg: {
    askAssetInfo?: AssetInfo;
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxSwapMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxSwapMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxSwapMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.swap(msg, fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxWithdrawLiquidityMutation {
  client: AstroportPairXykSaleTaxClient;
  msg: {
    assets?: Asset[];
    minAssetsToReceive?: Asset[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxWithdrawLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxWithdrawLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxWithdrawLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.withdrawLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxProvideLiquidityMutation {
  client: AstroportPairXykSaleTaxClient;
  msg: {
    assets: Asset[];
    autoStake?: boolean;
    minLpToReceive?: Uint128;
    receiver?: string;
    slippageTolerance?: Decimal;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxProvideLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxProvideLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxProvideLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.provideLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairXykSaleTaxReceiveMutation {
  client: AstroportPairXykSaleTaxClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairXykSaleTaxReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairXykSaleTaxReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairXykSaleTaxReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}