/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { InstantiateMsg, QueryMsg, SudoMsg, Uint128, Coin, ConfigResponse } from "./AstroportTokenfactoryTracker.types";
import { AstroportTokenfactoryTrackerQueryClient } from "./AstroportTokenfactoryTracker.client";
export const astroportTokenfactoryTrackerQueryKeys = {
  contract: ([{
    contract: "astroportTokenfactoryTracker"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportTokenfactoryTrackerQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  balanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportTokenfactoryTrackerQueryKeys.address(contractAddress)[0],
    method: "balance_at",
    args
  }] as const),
  totalSupplyAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportTokenfactoryTrackerQueryKeys.address(contractAddress)[0],
    method: "total_supply_at",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportTokenfactoryTrackerQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const)
};
export const astroportTokenfactoryTrackerQueries = {
  balanceAt: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportTokenfactoryTrackerBalanceAtQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportTokenfactoryTrackerQueryKeys.balanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.balanceAt({
      address: args.address,
      unit: args.unit
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  totalSupplyAt: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportTokenfactoryTrackerTotalSupplyAtQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportTokenfactoryTrackerQueryKeys.totalSupplyAt(client?.contractAddress, args),
    queryFn: () => client ? client.totalSupplyAt({
      unit: args.unit
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportTokenfactoryTrackerConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportTokenfactoryTrackerQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportTokenfactoryTrackerReactQuery<TResponse, TData = TResponse> {
  client: AstroportTokenfactoryTrackerQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportTokenfactoryTrackerConfigQuery<TData> extends AstroportTokenfactoryTrackerReactQuery<ConfigResponse, TData> {}
export function useAstroportTokenfactoryTrackerConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportTokenfactoryTrackerConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportTokenfactoryTrackerQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportTokenfactoryTrackerTotalSupplyAtQuery<TData> extends AstroportTokenfactoryTrackerReactQuery<Uint128, TData> {
  args: {
    unit?: number;
  };
}
export function useAstroportTokenfactoryTrackerTotalSupplyAtQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportTokenfactoryTrackerTotalSupplyAtQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportTokenfactoryTrackerQueryKeys.totalSupplyAt(client?.contractAddress, args), () => client ? client.totalSupplyAt({
    unit: args.unit
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportTokenfactoryTrackerBalanceAtQuery<TData> extends AstroportTokenfactoryTrackerReactQuery<Uint128, TData> {
  args: {
    address: string;
    unit?: number;
  };
}
export function useAstroportTokenfactoryTrackerBalanceAtQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportTokenfactoryTrackerBalanceAtQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportTokenfactoryTrackerQueryKeys.balanceAt(client?.contractAddress, args), () => client ? client.balanceAt({
    address: args.address,
    unit: args.unit
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}