/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AssetInfo = {
  token: {
    contract_addr: Addr;
  };
} | {
  native_token: {
    denom: string;
  };
};
export type Addr = string;
export interface InstantiateMsg {
  asset_infos: AssetInfo[];
  factory_contract: string;
}
export type ExecuteMsg = {
  update: {};
};
export type QueryMsg = {
  consult: {
    amount: Uint128;
    token: AssetInfo;
  };
};
export type Uint128 = string;
export interface MigrateMsg {}
export type Uint256 = string;
export type ArrayOfTupleOfAssetInfoAndUint256 = [AssetInfo, Uint256][];