/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee } from "@interchainjs/types";
import { AssetInfo, Addr, Uint128, InstantiateMsg, IncentivizationFeeInfo, Coin, ExecuteMsg, Binary, Cw20ReceiveMsg, InputSchedule, Asset, QueryMsg, ArrayOfTupleOfStringAndUint128, ArrayOfAssetInfo, Config, Decimal256, ArrayOfScheduleResponse, ScheduleResponse, Boolean, ArrayOfString, ArrayOfAsset, RewardType, PoolInfoResponse, RewardInfo, ArrayOfRewardInfo } from "./AstroportIncentives.types";
import { AstroportIncentivesQueryClient, AstroportIncentivesClient } from "./AstroportIncentives.client";
export const astroportIncentivesQueryKeys = {
  contract: ([{
    contract: "astroportIncentives"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportIncentivesQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  deposit: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "deposit",
    args
  }] as const),
  pendingRewards: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "pending_rewards",
    args
  }] as const),
  rewardInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "reward_info",
    args
  }] as const),
  poolInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "pool_info",
    args
  }] as const),
  poolStakers: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "pool_stakers",
    args
  }] as const),
  blockedTokensList: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "blocked_tokens_list",
    args
  }] as const),
  isFeeExpected: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "is_fee_expected",
    args
  }] as const),
  externalRewardSchedules: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "external_reward_schedules",
    args
  }] as const),
  listPools: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "list_pools",
    args
  }] as const),
  activePools: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportIncentivesQueryKeys.address(contractAddress)[0],
    method: "active_pools",
    args
  }] as const)
};
export const astroportIncentivesQueries = {
  config: <TData = Config,>({
    client,
    options
  }: AstroportIncentivesConfigQuery<TData>): UseQueryOptions<Config, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  deposit: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportIncentivesDepositQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.deposit(client?.contractAddress, args),
    queryFn: () => client ? client.deposit({
      lpToken: args.lpToken,
      user: args.user
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pendingRewards: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportIncentivesPendingRewardsQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.pendingRewards(client?.contractAddress, args),
    queryFn: () => client ? client.pendingRewards({
      lpToken: args.lpToken,
      user: args.user
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  rewardInfo: <TData = ArrayOfRewardInfo,>({
    client,
    args,
    options
  }: AstroportIncentivesRewardInfoQuery<TData>): UseQueryOptions<ArrayOfRewardInfo, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.rewardInfo(client?.contractAddress, args),
    queryFn: () => client ? client.rewardInfo({
      lpToken: args.lpToken
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  poolInfo: <TData = PoolInfoResponse,>({
    client,
    args,
    options
  }: AstroportIncentivesPoolInfoQuery<TData>): UseQueryOptions<PoolInfoResponse, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.poolInfo(client?.contractAddress, args),
    queryFn: () => client ? client.poolInfo({
      lpToken: args.lpToken
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  poolStakers: <TData = ArrayOfTupleOfStringAndUint128,>({
    client,
    args,
    options
  }: AstroportIncentivesPoolStakersQuery<TData>): UseQueryOptions<ArrayOfTupleOfStringAndUint128, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.poolStakers(client?.contractAddress, args),
    queryFn: () => client ? client.poolStakers({
      limit: args.limit,
      lpToken: args.lpToken,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  blockedTokensList: <TData = ArrayOfAssetInfo,>({
    client,
    args,
    options
  }: AstroportIncentivesBlockedTokensListQuery<TData>): UseQueryOptions<ArrayOfAssetInfo, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.blockedTokensList(client?.contractAddress, args),
    queryFn: () => client ? client.blockedTokensList({
      limit: args.limit,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  isFeeExpected: <TData = Boolean,>({
    client,
    args,
    options
  }: AstroportIncentivesIsFeeExpectedQuery<TData>): UseQueryOptions<Boolean, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.isFeeExpected(client?.contractAddress, args),
    queryFn: () => client ? client.isFeeExpected({
      lpToken: args.lpToken,
      reward: args.reward
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  externalRewardSchedules: <TData = ArrayOfScheduleResponse,>({
    client,
    args,
    options
  }: AstroportIncentivesExternalRewardSchedulesQuery<TData>): UseQueryOptions<ArrayOfScheduleResponse, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.externalRewardSchedules(client?.contractAddress, args),
    queryFn: () => client ? client.externalRewardSchedules({
      limit: args.limit,
      lpToken: args.lpToken,
      reward: args.reward,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  listPools: <TData = ArrayOfString,>({
    client,
    args,
    options
  }: AstroportIncentivesListPoolsQuery<TData>): UseQueryOptions<ArrayOfString, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.listPools(client?.contractAddress, args),
    queryFn: () => client ? client.listPools({
      limit: args.limit,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  activePools: <TData = ArrayOfTupleOfStringAndUint128,>({
    client,
    options
  }: AstroportIncentivesActivePoolsQuery<TData>): UseQueryOptions<ArrayOfTupleOfStringAndUint128, Error, TData> => ({
    queryKey: astroportIncentivesQueryKeys.activePools(client?.contractAddress),
    queryFn: () => client ? client.activePools() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportIncentivesReactQuery<TResponse, TData = TResponse> {
  client: AstroportIncentivesQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportIncentivesActivePoolsQuery<TData> extends AstroportIncentivesReactQuery<ArrayOfTupleOfStringAndUint128, TData> {}
export function useAstroportIncentivesActivePoolsQuery<TData = ArrayOfTupleOfStringAndUint128>({
  client,
  options
}: AstroportIncentivesActivePoolsQuery<TData>) {
  return useQuery<ArrayOfTupleOfStringAndUint128, Error, TData>(astroportIncentivesQueryKeys.activePools(client?.contractAddress), () => client ? client.activePools() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesListPoolsQuery<TData> extends AstroportIncentivesReactQuery<ArrayOfString, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useAstroportIncentivesListPoolsQuery<TData = ArrayOfString>({
  client,
  args,
  options
}: AstroportIncentivesListPoolsQuery<TData>) {
  return useQuery<ArrayOfString, Error, TData>(astroportIncentivesQueryKeys.listPools(client?.contractAddress, args), () => client ? client.listPools({
    limit: args.limit,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesExternalRewardSchedulesQuery<TData> extends AstroportIncentivesReactQuery<ArrayOfScheduleResponse, TData> {
  args: {
    limit?: number;
    lpToken: string;
    reward: string;
    startAfter?: number;
  };
}
export function useAstroportIncentivesExternalRewardSchedulesQuery<TData = ArrayOfScheduleResponse>({
  client,
  args,
  options
}: AstroportIncentivesExternalRewardSchedulesQuery<TData>) {
  return useQuery<ArrayOfScheduleResponse, Error, TData>(astroportIncentivesQueryKeys.externalRewardSchedules(client?.contractAddress, args), () => client ? client.externalRewardSchedules({
    limit: args.limit,
    lpToken: args.lpToken,
    reward: args.reward,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesIsFeeExpectedQuery<TData> extends AstroportIncentivesReactQuery<Boolean, TData> {
  args: {
    lpToken: string;
    reward: string;
  };
}
export function useAstroportIncentivesIsFeeExpectedQuery<TData = Boolean>({
  client,
  args,
  options
}: AstroportIncentivesIsFeeExpectedQuery<TData>) {
  return useQuery<Boolean, Error, TData>(astroportIncentivesQueryKeys.isFeeExpected(client?.contractAddress, args), () => client ? client.isFeeExpected({
    lpToken: args.lpToken,
    reward: args.reward
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesBlockedTokensListQuery<TData> extends AstroportIncentivesReactQuery<ArrayOfAssetInfo, TData> {
  args: {
    limit?: number;
    startAfter?: AssetInfo;
  };
}
export function useAstroportIncentivesBlockedTokensListQuery<TData = ArrayOfAssetInfo>({
  client,
  args,
  options
}: AstroportIncentivesBlockedTokensListQuery<TData>) {
  return useQuery<ArrayOfAssetInfo, Error, TData>(astroportIncentivesQueryKeys.blockedTokensList(client?.contractAddress, args), () => client ? client.blockedTokensList({
    limit: args.limit,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesPoolStakersQuery<TData> extends AstroportIncentivesReactQuery<ArrayOfTupleOfStringAndUint128, TData> {
  args: {
    limit?: number;
    lpToken: string;
    startAfter?: string;
  };
}
export function useAstroportIncentivesPoolStakersQuery<TData = ArrayOfTupleOfStringAndUint128>({
  client,
  args,
  options
}: AstroportIncentivesPoolStakersQuery<TData>) {
  return useQuery<ArrayOfTupleOfStringAndUint128, Error, TData>(astroportIncentivesQueryKeys.poolStakers(client?.contractAddress, args), () => client ? client.poolStakers({
    limit: args.limit,
    lpToken: args.lpToken,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesPoolInfoQuery<TData> extends AstroportIncentivesReactQuery<PoolInfoResponse, TData> {
  args: {
    lpToken: string;
  };
}
export function useAstroportIncentivesPoolInfoQuery<TData = PoolInfoResponse>({
  client,
  args,
  options
}: AstroportIncentivesPoolInfoQuery<TData>) {
  return useQuery<PoolInfoResponse, Error, TData>(astroportIncentivesQueryKeys.poolInfo(client?.contractAddress, args), () => client ? client.poolInfo({
    lpToken: args.lpToken
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesRewardInfoQuery<TData> extends AstroportIncentivesReactQuery<ArrayOfRewardInfo, TData> {
  args: {
    lpToken: string;
  };
}
export function useAstroportIncentivesRewardInfoQuery<TData = ArrayOfRewardInfo>({
  client,
  args,
  options
}: AstroportIncentivesRewardInfoQuery<TData>) {
  return useQuery<ArrayOfRewardInfo, Error, TData>(astroportIncentivesQueryKeys.rewardInfo(client?.contractAddress, args), () => client ? client.rewardInfo({
    lpToken: args.lpToken
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesPendingRewardsQuery<TData> extends AstroportIncentivesReactQuery<ArrayOfAsset, TData> {
  args: {
    lpToken: string;
    user: string;
  };
}
export function useAstroportIncentivesPendingRewardsQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportIncentivesPendingRewardsQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportIncentivesQueryKeys.pendingRewards(client?.contractAddress, args), () => client ? client.pendingRewards({
    lpToken: args.lpToken,
    user: args.user
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesDepositQuery<TData> extends AstroportIncentivesReactQuery<Uint128, TData> {
  args: {
    lpToken: string;
    user: string;
  };
}
export function useAstroportIncentivesDepositQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportIncentivesDepositQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportIncentivesQueryKeys.deposit(client?.contractAddress, args), () => client ? client.deposit({
    lpToken: args.lpToken,
    user: args.user
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesConfigQuery<TData> extends AstroportIncentivesReactQuery<Config, TData> {}
export function useAstroportIncentivesConfigQuery<TData = Config>({
  client,
  options
}: AstroportIncentivesConfigQuery<TData>) {
  return useQuery<Config, Error, TData>(astroportIncentivesQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportIncentivesClaimOwnershipMutation {
  client: AstroportIncentivesClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportIncentivesDropOwnershipProposalMutation {
  client: AstroportIncentivesClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportIncentivesProposeNewOwnerMutation {
  client: AstroportIncentivesClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesDeactivateBlockedPoolsMutation {
  client: AstroportIncentivesClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesDeactivateBlockedPoolsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesDeactivateBlockedPoolsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesDeactivateBlockedPoolsMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.deactivateBlockedPools(fee, memo, funds), options);
}
export interface AstroportIncentivesDeactivatePoolMutation {
  client: AstroportIncentivesClient;
  msg: {
    lpToken: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesDeactivatePoolMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesDeactivatePoolMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesDeactivatePoolMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.deactivatePool(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesUpdateBlockedTokenslistMutation {
  client: AstroportIncentivesClient;
  msg: {
    add?: AssetInfo[];
    remove?: AssetInfo[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesUpdateBlockedTokenslistMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesUpdateBlockedTokenslistMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesUpdateBlockedTokenslistMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateBlockedTokenslist(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesUpdateConfigMutation {
  client: AstroportIncentivesClient;
  msg: {
    astroToken?: AssetInfo;
    generatorController?: string;
    guardian?: string;
    incentivizationFeeInfo?: IncentivizationFeeInfo;
    tokenTransferGasLimit?: number;
    vestingContract?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesClaimOrphanedRewardsMutation {
  client: AstroportIncentivesClient;
  msg: {
    limit?: number;
    receiver: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesClaimOrphanedRewardsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesClaimOrphanedRewardsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesClaimOrphanedRewardsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOrphanedRewards(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesRemoveRewardFromPoolMutation {
  client: AstroportIncentivesClient;
  msg: {
    bypassUpcomingSchedules: boolean;
    lpToken: string;
    receiver: string;
    reward: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesRemoveRewardFromPoolMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesRemoveRewardFromPoolMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesRemoveRewardFromPoolMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.removeRewardFromPool(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesIncentivizeManyMutation {
  client: AstroportIncentivesClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesIncentivizeManyMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesIncentivizeManyMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesIncentivizeManyMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.incentivizeMany(fee, memo, funds), options);
}
export interface AstroportIncentivesIncentivizeMutation {
  client: AstroportIncentivesClient;
  msg: {
    lpToken: string;
    schedule: InputSchedule;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesIncentivizeMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesIncentivizeMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesIncentivizeMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.incentivize(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesSetTokensPerSecondMutation {
  client: AstroportIncentivesClient;
  msg: {
    amount: Uint128;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesSetTokensPerSecondMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesSetTokensPerSecondMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesSetTokensPerSecondMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.setTokensPerSecond(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesWithdrawMutation {
  client: AstroportIncentivesClient;
  msg: {
    amount: Uint128;
    lpToken: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesWithdrawMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesWithdrawMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesWithdrawMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.withdraw(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesDepositMutation {
  client: AstroportIncentivesClient;
  msg: {
    recipient?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesDepositMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesDepositMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesDepositMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.deposit(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesReceiveMutation {
  client: AstroportIncentivesClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesClaimRewardsMutation {
  client: AstroportIncentivesClient;
  msg: {
    lpTokens: string[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesClaimRewardsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesClaimRewardsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesClaimRewardsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimRewards(msg, fee, memo, funds), options);
}
export interface AstroportIncentivesSetupPoolsMutation {
  client: AstroportIncentivesClient;
  msg: {
    pools: string[][];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportIncentivesSetupPoolsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportIncentivesSetupPoolsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportIncentivesSetupPoolsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.setupPools(msg, fee, memo, funds), options);
}