/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient } from "./baseClient";
import { InstantiateMsg, QueryMsg, SudoMsg, Uint128, Coin, ConfigResponse } from "./AstroportTokenfactoryTracker.types";
export interface AstroportTokenfactoryTrackerReadOnlyInterface {
  contractAddress: string;
  balanceAt: ({
    address,
    unit
  }: {
    address: string;
    unit?: number;
  }) => Promise<Uint128>;
  totalSupplyAt: ({
    unit
  }: {
    unit?: number;
  }) => Promise<Uint128>;
  config: () => Promise<ConfigResponse>;
}
export class AstroportTokenfactoryTrackerQueryClient implements AstroportTokenfactoryTrackerReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.balanceAt = this.balanceAt.bind(this);
    this.totalSupplyAt = this.totalSupplyAt.bind(this);
    this.config = this.config.bind(this);
  }
  balanceAt = async ({
    address,
    unit
  }: {
    address: string;
    unit?: number;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance_at: {
        address,
        unit
      }
    });
  };
  totalSupplyAt = async ({
    unit
  }: {
    unit?: number;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_supply_at: {
        unit
      }
    });
  };
  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
}