/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, CosmosMsgForNeutronMsg, BankMsg, Uint128, NeutronMsg, Binary, AdminProposal, StakingMsg, DistributionMsg, IbcMsg, Timestamp, Uint64, WasmMsg, GovMsg, VoteOption, Coin, IbcFee, ProtobufAny, KVKey, RequestPacketTimeoutHeight, ParamChangeProposal, ParamChange, UpgradeProposal, Plan, ClientUpdateProposal, ProposalExecuteMessage, SoftwareUpgradeProposal, CancelSoftwareUpgradeProposal, PinCodesProposal, UnpinCodesProposal, SudoContractProposal, UpdateAdminProposal, ClearAdminProposal, DenomUnit, MsgExecuteContract, IbcTimeout, IbcTimeoutBlock, QueryMsg, CosmosMsgForEmpty, Empty, AdminListResponse, CanExecuteResponse } from "./AstroportWhitelist.types";
import { AstroportWhitelistQueryClient, AstroportWhitelistClient } from "./AstroportWhitelist.client";
export const astroportWhitelistQueryKeys = {
  contract: ([{
    contract: "astroportWhitelist"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportWhitelistQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  adminList: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportWhitelistQueryKeys.address(contractAddress)[0],
    method: "admin_list",
    args
  }] as const),
  canExecute: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportWhitelistQueryKeys.address(contractAddress)[0],
    method: "can_execute",
    args
  }] as const)
};
export const astroportWhitelistQueries = {
  adminList: <TData = AdminListResponse,>({
    client,
    options
  }: AstroportWhitelistAdminListQuery<TData>): UseQueryOptions<AdminListResponse, Error, TData> => ({
    queryKey: astroportWhitelistQueryKeys.adminList(client?.contractAddress),
    queryFn: () => client ? client.adminList() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  canExecute: <TData = CanExecuteResponse,>({
    client,
    args,
    options
  }: AstroportWhitelistCanExecuteQuery<TData>): UseQueryOptions<CanExecuteResponse, Error, TData> => ({
    queryKey: astroportWhitelistQueryKeys.canExecute(client?.contractAddress, args),
    queryFn: () => client ? client.canExecute({
      msg: args.msg,
      sender: args.sender
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportWhitelistReactQuery<TResponse, TData = TResponse> {
  client: AstroportWhitelistQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportWhitelistCanExecuteQuery<TData> extends AstroportWhitelistReactQuery<CanExecuteResponse, TData> {
  args: {
    msg: CosmosMsgForEmpty;
    sender: string;
  };
}
export function useAstroportWhitelistCanExecuteQuery<TData = CanExecuteResponse>({
  client,
  args,
  options
}: AstroportWhitelistCanExecuteQuery<TData>) {
  return useQuery<CanExecuteResponse, Error, TData>(astroportWhitelistQueryKeys.canExecute(client?.contractAddress, args), () => client ? client.canExecute({
    msg: args.msg,
    sender: args.sender
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportWhitelistAdminListQuery<TData> extends AstroportWhitelistReactQuery<AdminListResponse, TData> {}
export function useAstroportWhitelistAdminListQuery<TData = AdminListResponse>({
  client,
  options
}: AstroportWhitelistAdminListQuery<TData>) {
  return useQuery<AdminListResponse, Error, TData>(astroportWhitelistQueryKeys.adminList(client?.contractAddress), () => client ? client.adminList() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportWhitelistUpdateAdminsMutation {
  client: AstroportWhitelistClient;
  msg: {
    admins: string[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportWhitelistUpdateAdminsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportWhitelistUpdateAdminsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportWhitelistUpdateAdminsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateAdmins(msg, fee, memo, funds), options);
}
export interface AstroportWhitelistFreezeMutation {
  client: AstroportWhitelistClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportWhitelistFreezeMutation(options?: Omit<UseMutationOptions<any, Error, AstroportWhitelistFreezeMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportWhitelistFreezeMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.freeze(fee, memo, funds), options);
}
export interface AstroportWhitelistExecuteMutation {
  client: AstroportWhitelistClient;
  msg: {
    msgs: CosmosMsgForNeutronMsg[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportWhitelistExecuteMutation(options?: Omit<UseMutationOptions<any, Error, AstroportWhitelistExecuteMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportWhitelistExecuteMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.execute(msg, fee, memo, funds), options);
}