/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Binary, QueryMsg, Uint128, Config, TrackerData } from "./AstroportStaking.types";
export interface AstroportStakingReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  totalShares: () => Promise<Uint128>;
  totalDeposit: () => Promise<Uint128>;
  trackerConfig: () => Promise<TrackerData>;
  balanceAt: ({
    address,
    timestamp
  }: {
    address: string;
    timestamp?: number;
  }) => Promise<Uint128>;
  totalSupplyAt: ({
    timestamp
  }: {
    timestamp?: number;
  }) => Promise<Uint128>;
}
export class AstroportStakingQueryClient implements AstroportStakingReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.totalShares = this.totalShares.bind(this);
    this.totalDeposit = this.totalDeposit.bind(this);
    this.trackerConfig = this.trackerConfig.bind(this);
    this.balanceAt = this.balanceAt.bind(this);
    this.totalSupplyAt = this.totalSupplyAt.bind(this);
  }
  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  totalShares = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_shares: {}
    });
  };
  totalDeposit = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_deposit: {}
    });
  };
  trackerConfig = async (): Promise<TrackerData> => {
    return this.client.queryContractSmart(this.contractAddress, {
      tracker_config: {}
    });
  };
  balanceAt = async ({
    address,
    timestamp
  }: {
    address: string;
    timestamp?: number;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      balance_at: {
        address,
        timestamp
      }
    });
  };
  totalSupplyAt = async ({
    timestamp
  }: {
    timestamp?: number;
  }): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_supply_at: {
        timestamp
      }
    });
  };
}
export interface AstroportStakingInterface {
  contractAddress: string;
  sender: string;
  enter: ({
    receiver
  }: {
    receiver?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  enterWithHook: ({
    contractAddress,
    msg
  }: {
    contractAddress: string;
    msg: Binary;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  leave: ({
    receiver
  }: {
    receiver?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroportStakingClient implements AstroportStakingInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.enter = this.enter.bind(this);
    this.enterWithHook = this.enterWithHook.bind(this);
    this.leave = this.leave.bind(this);
  }
  enter = async ({
    receiver
  }: {
    receiver?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      enter: {
        receiver
      }
    }, fee_, memo_, funds_);
  };
  enterWithHook = async ({
    contractAddress,
    msg
  }: {
    contractAddress: string;
    msg: Binary;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      enter_with_hook: {
        contract_address: contractAddress,
        msg
      }
    }, fee_, memo_, funds_);
  };
  leave = async ({
    receiver
  }: {
    receiver?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      leave: {
        receiver
      }
    }, fee_, memo_, funds_);
  };
}