/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  tokenfactory_module_address: string;
  track_over_seconds?: boolean;
  tracked_denom: string;
}
export type QueryMsg = {
  balance_at: {
    address: string;
    unit?: number | null;
  };
} | {
  total_supply_at: {
    unit?: number | null;
  };
} | {
  config: {};
};
export type SudoMsg = {
  block_before_send: {
    amount: Coin;
    from: string;
    to: string;
  };
} | {
  track_before_send: {
    amount: Coin;
    from: string;
    to: string;
  };
};
export type Uint128 = string;
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface ConfigResponse {
  token_factory_module: string;
  track_over_seconds: boolean;
  tracked_denom: string;
}