/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, Config, CoinResponse, ArrayOfCoinResponse } from "./AstroportNativeCoinRegistry.types";
import { AstroportNativeCoinRegistryQueryClient, AstroportNativeCoinRegistryClient } from "./AstroportNativeCoinRegistry.client";
export const astroportNativeCoinRegistryQueryKeys = {
  contract: ([{
    contract: "astroportNativeCoinRegistry"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportNativeCoinRegistryQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportNativeCoinRegistryQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  nativeToken: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportNativeCoinRegistryQueryKeys.address(contractAddress)[0],
    method: "native_token",
    args
  }] as const),
  nativeTokens: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportNativeCoinRegistryQueryKeys.address(contractAddress)[0],
    method: "native_tokens",
    args
  }] as const)
};
export const astroportNativeCoinRegistryQueries = {
  config: <TData = Config,>({
    client,
    options
  }: AstroportNativeCoinRegistryConfigQuery<TData>): UseQueryOptions<Config, Error, TData> => ({
    queryKey: astroportNativeCoinRegistryQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  nativeToken: <TData = CoinResponse,>({
    client,
    args,
    options
  }: AstroportNativeCoinRegistryNativeTokenQuery<TData>): UseQueryOptions<CoinResponse, Error, TData> => ({
    queryKey: astroportNativeCoinRegistryQueryKeys.nativeToken(client?.contractAddress, args),
    queryFn: () => client ? client.nativeToken({
      denom: args.denom
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  nativeTokens: <TData = ArrayOfCoinResponse,>({
    client,
    args,
    options
  }: AstroportNativeCoinRegistryNativeTokensQuery<TData>): UseQueryOptions<ArrayOfCoinResponse, Error, TData> => ({
    queryKey: astroportNativeCoinRegistryQueryKeys.nativeTokens(client?.contractAddress, args),
    queryFn: () => client ? client.nativeTokens({
      limit: args.limit,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportNativeCoinRegistryReactQuery<TResponse, TData = TResponse> {
  client: AstroportNativeCoinRegistryQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportNativeCoinRegistryNativeTokensQuery<TData> extends AstroportNativeCoinRegistryReactQuery<ArrayOfCoinResponse, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useAstroportNativeCoinRegistryNativeTokensQuery<TData = ArrayOfCoinResponse>({
  client,
  args,
  options
}: AstroportNativeCoinRegistryNativeTokensQuery<TData>) {
  return useQuery<ArrayOfCoinResponse, Error, TData>(astroportNativeCoinRegistryQueryKeys.nativeTokens(client?.contractAddress, args), () => client ? client.nativeTokens({
    limit: args.limit,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportNativeCoinRegistryNativeTokenQuery<TData> extends AstroportNativeCoinRegistryReactQuery<CoinResponse, TData> {
  args: {
    denom: string;
  };
}
export function useAstroportNativeCoinRegistryNativeTokenQuery<TData = CoinResponse>({
  client,
  args,
  options
}: AstroportNativeCoinRegistryNativeTokenQuery<TData>) {
  return useQuery<CoinResponse, Error, TData>(astroportNativeCoinRegistryQueryKeys.nativeToken(client?.contractAddress, args), () => client ? client.nativeToken({
    denom: args.denom
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportNativeCoinRegistryConfigQuery<TData> extends AstroportNativeCoinRegistryReactQuery<Config, TData> {}
export function useAstroportNativeCoinRegistryConfigQuery<TData = Config>({
  client,
  options
}: AstroportNativeCoinRegistryConfigQuery<TData>) {
  return useQuery<Config, Error, TData>(astroportNativeCoinRegistryQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportNativeCoinRegistryClaimOwnershipMutation {
  client: AstroportNativeCoinRegistryClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportNativeCoinRegistryClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportNativeCoinRegistryClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportNativeCoinRegistryClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportNativeCoinRegistryDropOwnershipProposalMutation {
  client: AstroportNativeCoinRegistryClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportNativeCoinRegistryDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportNativeCoinRegistryDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportNativeCoinRegistryDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportNativeCoinRegistryProposeNewOwnerMutation {
  client: AstroportNativeCoinRegistryClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportNativeCoinRegistryProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportNativeCoinRegistryProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportNativeCoinRegistryProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportNativeCoinRegistryRemoveMutation {
  client: AstroportNativeCoinRegistryClient;
  msg: {
    nativeCoins: string[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportNativeCoinRegistryRemoveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportNativeCoinRegistryRemoveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportNativeCoinRegistryRemoveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.remove(msg, fee, memo, funds), options);
}
export interface AstroportNativeCoinRegistryRegisterMutation {
  client: AstroportNativeCoinRegistryClient;
  msg: {
    nativeCoins: string[][];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportNativeCoinRegistryRegisterMutation(options?: Omit<UseMutationOptions<any, Error, AstroportNativeCoinRegistryRegisterMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportNativeCoinRegistryRegisterMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.register(msg, fee, memo, funds), options);
}
export interface AstroportNativeCoinRegistryAddMutation {
  client: AstroportNativeCoinRegistryClient;
  msg: {
    nativeCoins: string[][];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportNativeCoinRegistryAddMutation(options?: Omit<UseMutationOptions<any, Error, AstroportNativeCoinRegistryAddMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportNativeCoinRegistryAddMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.add(msg, fee, memo, funds), options);
}