/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  deposit_token_denom: string;
  token_factory_addr: string;
  tracking_admin: string;
  tracking_code_id: number;
}
export type ExecuteMsg = {
  enter: {
    receiver?: string | null;
  };
} | {
  enter_with_hook: {
    contract_address: string;
    msg: Binary;
  };
} | {
  leave: {
    receiver?: string | null;
  };
};
export type Binary = string;
export type QueryMsg = {
  config: {};
} | {
  total_shares: {};
} | {
  total_deposit: {};
} | {
  tracker_config: {};
} | {
  balance_at: {
    address: string;
    timestamp?: number | null;
  };
} | {
  total_supply_at: {
    timestamp?: number | null;
  };
};
export type Uint128 = string;
export interface Config {
  astro_denom: string;
  xastro_denom: string;
}
export interface TrackerData {
  admin: string;
  code_id: number;
  token_factory_addr: string;
  tracker_addr: string;
}