/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { Coin, StdFee } from "@interchainjs/types";
import { AssetInfo, Addr, InstantiateMsg, ExecuteMsg, QueryMsg, Uint128, MigrateMsg, Uint256, ArrayOfTupleOfAssetInfoAndUint256 } from "./AstroportOracle.types";
export interface AstroportOracleReadOnlyInterface {
  contractAddress: string;
  consult: ({
    amount,
    token
  }: {
    amount: Uint128;
    token: AssetInfo;
  }) => Promise<ArrayOfTupleOfAssetInfoAndUint256>;
}
export class AstroportOracleQueryClient implements AstroportOracleReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.consult = this.consult.bind(this);
  }
  consult = async ({
    amount,
    token
  }: {
    amount: Uint128;
    token: AssetInfo;
  }): Promise<ArrayOfTupleOfAssetInfoAndUint256> => {
    return this.client.queryContractSmart(this.contractAddress, {
      consult: {
        amount,
        token
      }
    });
  };
}
export interface AstroportOracleInterface {
  contractAddress: string;
  sender: string;
  update: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroportOracleClient implements AstroportOracleInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.update = this.update.bind(this);
  }
  update = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update: {}
    }, fee_, memo_, funds_);
  };
}