/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type AssetInfo = {
  token: {
    contract_addr: Addr;
  };
} | {
  native_token: {
    denom: string;
  };
};
export type Addr = string;
export interface InstantiateMsg {
  new_astro_denom: string;
  old_astro_asset_info: AssetInfo;
  outpost_burn_params?: OutpostBurnParams | null;
}
export interface OutpostBurnParams {
  old_astro_transfer_channel: string;
  terra_burn_addr: string;
}
export type ExecuteMsg = {
  convert: {
    receiver?: string | null;
  };
} | {
  receive: Cw20ReceiveMsg;
} | {
  transfer_for_burning: {
    timeout?: number | null;
  };
} | {
  burn: {};
};
export type Uint128 = string;
export type Binary = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}