/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, Binary, PairType, InstantiateMsg, ExecuteMsg, Uint128, Decimal, DualityPairMsg, Cw20ReceiveMsg, Asset, UpdateDualityOrderbook, QueryMsg, Uint64, NullableUint128, ConfigResponse, CumulativePricesResponse, OracleObservation, PairInfo, PoolResponse, ReverseSimulationResponse, ArrayOfAsset, SimulationResponse } from "./AstroportPairConcentratedDuality.types";
import { AstroportPairConcentratedDualityQueryClient, AstroportPairConcentratedDualityClient } from "./AstroportPairConcentratedDuality.client";
export const astroportPairConcentratedDualityQueryKeys = {
  contract: ([{
    contract: "astroportPairConcentratedDuality"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportPairConcentratedDualityQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  pair: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "pair",
    args
  }] as const),
  pool: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "pool",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  share: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "share",
    args
  }] as const),
  simulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "simulation",
    args
  }] as const),
  reverseSimulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "reverse_simulation",
    args
  }] as const),
  cumulativePrices: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "cumulative_prices",
    args
  }] as const),
  queryComputeD: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "query_compute_d",
    args
  }] as const),
  assetBalanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "asset_balance_at",
    args
  }] as const),
  observe: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "observe",
    args
  }] as const),
  simulateWithdraw: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "simulate_withdraw",
    args
  }] as const),
  simulateProvide: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedDualityQueryKeys.address(contractAddress)[0],
    method: "simulate_provide",
    args
  }] as const)
};
export const astroportPairConcentratedDualityQueries = {
  pair: <TData = PairInfo,>({
    client,
    options
  }: AstroportPairConcentratedDualityPairQuery<TData>): UseQueryOptions<PairInfo, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.pair(client?.contractAddress),
    queryFn: () => client ? client.pair() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pool: <TData = PoolResponse,>({
    client,
    options
  }: AstroportPairConcentratedDualityPoolQuery<TData>): UseQueryOptions<PoolResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.pool(client?.contractAddress),
    queryFn: () => client ? client.pool() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportPairConcentratedDualityConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  share: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairConcentratedDualityShareQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.share(client?.contractAddress, args),
    queryFn: () => client ? client.share({
      amount: args.amount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulation: <TData = SimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConcentratedDualitySimulationQuery<TData>): UseQueryOptions<SimulationResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.simulation(client?.contractAddress, args),
    queryFn: () => client ? client.simulation({
      askAssetInfo: args.askAssetInfo,
      offerAsset: args.offerAsset
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseSimulation: <TData = ReverseSimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConcentratedDualityReverseSimulationQuery<TData>): UseQueryOptions<ReverseSimulationResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.reverseSimulation(client?.contractAddress, args),
    queryFn: () => client ? client.reverseSimulation({
      askAsset: args.askAsset,
      offerAssetInfo: args.offerAssetInfo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  cumulativePrices: <TData = CumulativePricesResponse,>({
    client,
    options
  }: AstroportPairConcentratedDualityCumulativePricesQuery<TData>): UseQueryOptions<CumulativePricesResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.cumulativePrices(client?.contractAddress),
    queryFn: () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  queryComputeD: <TData = Uint128,>({
    client,
    options
  }: AstroportPairConcentratedDualityQueryComputeDQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.queryComputeD(client?.contractAddress),
    queryFn: () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  assetBalanceAt: <TData = NullableUint128,>({
    client,
    args,
    options
  }: AstroportPairConcentratedDualityAssetBalanceAtQuery<TData>): UseQueryOptions<NullableUint128, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.assetBalanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.assetBalanceAt({
      assetInfo: args.assetInfo,
      blockHeight: args.blockHeight
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  observe: <TData = OracleObservation,>({
    client,
    args,
    options
  }: AstroportPairConcentratedDualityObserveQuery<TData>): UseQueryOptions<OracleObservation, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.observe(client?.contractAddress, args),
    queryFn: () => client ? client.observe({
      secondsAgo: args.secondsAgo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateWithdraw: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairConcentratedDualitySimulateWithdrawQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.simulateWithdraw(client?.contractAddress, args),
    queryFn: () => client ? client.simulateWithdraw({
      lpAmount: args.lpAmount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateProvide: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportPairConcentratedDualitySimulateProvideQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairConcentratedDualityQueryKeys.simulateProvide(client?.contractAddress, args),
    queryFn: () => client ? client.simulateProvide({
      assets: args.assets,
      slippageTolerance: args.slippageTolerance
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportPairConcentratedDualityReactQuery<TResponse, TData = TResponse> {
  client: AstroportPairConcentratedDualityQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportPairConcentratedDualitySimulateProvideQuery<TData> extends AstroportPairConcentratedDualityReactQuery<Uint128, TData> {
  args: {
    assets: Asset[];
    slippageTolerance?: Decimal;
  };
}
export function useAstroportPairConcentratedDualitySimulateProvideQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportPairConcentratedDualitySimulateProvideQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairConcentratedDualityQueryKeys.simulateProvide(client?.contractAddress, args), () => client ? client.simulateProvide({
    assets: args.assets,
    slippageTolerance: args.slippageTolerance
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualitySimulateWithdrawQuery<TData> extends AstroportPairConcentratedDualityReactQuery<ArrayOfAsset, TData> {
  args: {
    lpAmount: Uint128;
  };
}
export function useAstroportPairConcentratedDualitySimulateWithdrawQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairConcentratedDualitySimulateWithdrawQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairConcentratedDualityQueryKeys.simulateWithdraw(client?.contractAddress, args), () => client ? client.simulateWithdraw({
    lpAmount: args.lpAmount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityObserveQuery<TData> extends AstroportPairConcentratedDualityReactQuery<OracleObservation, TData> {
  args: {
    secondsAgo: number;
  };
}
export function useAstroportPairConcentratedDualityObserveQuery<TData = OracleObservation>({
  client,
  args,
  options
}: AstroportPairConcentratedDualityObserveQuery<TData>) {
  return useQuery<OracleObservation, Error, TData>(astroportPairConcentratedDualityQueryKeys.observe(client?.contractAddress, args), () => client ? client.observe({
    secondsAgo: args.secondsAgo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityAssetBalanceAtQuery<TData> extends AstroportPairConcentratedDualityReactQuery<NullableUint128, TData> {
  args: {
    assetInfo: AssetInfo;
    blockHeight: Uint64;
  };
}
export function useAstroportPairConcentratedDualityAssetBalanceAtQuery<TData = NullableUint128>({
  client,
  args,
  options
}: AstroportPairConcentratedDualityAssetBalanceAtQuery<TData>) {
  return useQuery<NullableUint128, Error, TData>(astroportPairConcentratedDualityQueryKeys.assetBalanceAt(client?.contractAddress, args), () => client ? client.assetBalanceAt({
    assetInfo: args.assetInfo,
    blockHeight: args.blockHeight
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityQueryComputeDQuery<TData> extends AstroportPairConcentratedDualityReactQuery<Uint128, TData> {}
export function useAstroportPairConcentratedDualityQueryComputeDQuery<TData = Uint128>({
  client,
  options
}: AstroportPairConcentratedDualityQueryComputeDQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairConcentratedDualityQueryKeys.queryComputeD(client?.contractAddress), () => client ? client.queryComputeD() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityCumulativePricesQuery<TData> extends AstroportPairConcentratedDualityReactQuery<CumulativePricesResponse, TData> {}
export function useAstroportPairConcentratedDualityCumulativePricesQuery<TData = CumulativePricesResponse>({
  client,
  options
}: AstroportPairConcentratedDualityCumulativePricesQuery<TData>) {
  return useQuery<CumulativePricesResponse, Error, TData>(astroportPairConcentratedDualityQueryKeys.cumulativePrices(client?.contractAddress), () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityReverseSimulationQuery<TData> extends AstroportPairConcentratedDualityReactQuery<ReverseSimulationResponse, TData> {
  args: {
    askAsset: Asset;
    offerAssetInfo?: AssetInfo;
  };
}
export function useAstroportPairConcentratedDualityReverseSimulationQuery<TData = ReverseSimulationResponse>({
  client,
  args,
  options
}: AstroportPairConcentratedDualityReverseSimulationQuery<TData>) {
  return useQuery<ReverseSimulationResponse, Error, TData>(astroportPairConcentratedDualityQueryKeys.reverseSimulation(client?.contractAddress, args), () => client ? client.reverseSimulation({
    askAsset: args.askAsset,
    offerAssetInfo: args.offerAssetInfo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualitySimulationQuery<TData> extends AstroportPairConcentratedDualityReactQuery<SimulationResponse, TData> {
  args: {
    askAssetInfo?: AssetInfo;
    offerAsset: Asset;
  };
}
export function useAstroportPairConcentratedDualitySimulationQuery<TData = SimulationResponse>({
  client,
  args,
  options
}: AstroportPairConcentratedDualitySimulationQuery<TData>) {
  return useQuery<SimulationResponse, Error, TData>(astroportPairConcentratedDualityQueryKeys.simulation(client?.contractAddress, args), () => client ? client.simulation({
    askAssetInfo: args.askAssetInfo,
    offerAsset: args.offerAsset
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityShareQuery<TData> extends AstroportPairConcentratedDualityReactQuery<ArrayOfAsset, TData> {
  args: {
    amount: Uint128;
  };
}
export function useAstroportPairConcentratedDualityShareQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairConcentratedDualityShareQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairConcentratedDualityQueryKeys.share(client?.contractAddress, args), () => client ? client.share({
    amount: args.amount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityConfigQuery<TData> extends AstroportPairConcentratedDualityReactQuery<ConfigResponse, TData> {}
export function useAstroportPairConcentratedDualityConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportPairConcentratedDualityConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportPairConcentratedDualityQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityPoolQuery<TData> extends AstroportPairConcentratedDualityReactQuery<PoolResponse, TData> {}
export function useAstroportPairConcentratedDualityPoolQuery<TData = PoolResponse>({
  client,
  options
}: AstroportPairConcentratedDualityPoolQuery<TData>) {
  return useQuery<PoolResponse, Error, TData>(astroportPairConcentratedDualityQueryKeys.pool(client?.contractAddress), () => client ? client.pool() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityPairQuery<TData> extends AstroportPairConcentratedDualityReactQuery<PairInfo, TData> {}
export function useAstroportPairConcentratedDualityPairQuery<TData = PairInfo>({
  client,
  options
}: AstroportPairConcentratedDualityPairQuery<TData>) {
  return useQuery<PairInfo, Error, TData>(astroportPairConcentratedDualityQueryKeys.pair(client?.contractAddress), () => client ? client.pair() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedDualityCustomMutation {
  client: AstroportPairConcentratedDualityClient;
  msg: DualityPairMsg;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityCustomMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityCustomMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityCustomMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.custom(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualityClaimOwnershipMutation {
  client: AstroportPairConcentratedDualityClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualityDropOwnershipProposalMutation {
  client: AstroportPairConcentratedDualityClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualityProposeNewOwnerMutation {
  client: AstroportPairConcentratedDualityClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualityUpdateConfigMutation {
  client: AstroportPairConcentratedDualityClient;
  msg: {
    params: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualitySwapMutation {
  client: AstroportPairConcentratedDualityClient;
  msg: {
    askAssetInfo?: AssetInfo;
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualitySwapMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualitySwapMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualitySwapMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.swap(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualityWithdrawLiquidityMutation {
  client: AstroportPairConcentratedDualityClient;
  msg: {
    assets?: Asset[];
    minAssetsToReceive?: Asset[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityWithdrawLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityWithdrawLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityWithdrawLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.withdrawLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualityProvideLiquidityMutation {
  client: AstroportPairConcentratedDualityClient;
  msg: {
    assets: Asset[];
    autoStake?: boolean;
    minLpToReceive?: Uint128;
    receiver?: string;
    slippageTolerance?: Decimal;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityProvideLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityProvideLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityProvideLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.provideLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedDualityReceiveMutation {
  client: AstroportPairConcentratedDualityClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedDualityReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedDualityReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedDualityReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}