/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { Uint128, Logo, EmbeddedLogo, Binary, InstantiateMsg, Cw20Coin, InstantiateMarketingInfo, MinterResponse, ExecuteMsg, Expiration, Timestamp, Uint64, QueryMsg, AllAccountsResponse, AllAllowancesResponse, AllowanceInfo, AllowanceResponse, BalanceResponse, DownloadLogoResponse, LogoInfo, Addr, MarketingInfoResponse, NullableMinterResponse, TokenInfoResponse } from "./AstroportXastroToken.types";
import { AstroportXastroTokenQueryClient, AstroportXastroTokenClient } from "./AstroportXastroToken.client";
export const astroportXastroTokenQueryKeys = {
  contract: ([{
    contract: "astroportXastroToken"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportXastroTokenQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  balance: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "balance",
    args
  }] as const),
  balanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "balance_at",
    args
  }] as const),
  totalSupplyAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "total_supply_at",
    args
  }] as const),
  tokenInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "token_info",
    args
  }] as const),
  minter: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "minter",
    args
  }] as const),
  allowance: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "allowance",
    args
  }] as const),
  allAllowances: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "all_allowances",
    args
  }] as const),
  allAccounts: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "all_accounts",
    args
  }] as const),
  marketingInfo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "marketing_info",
    args
  }] as const),
  downloadLogo: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportXastroTokenQueryKeys.address(contractAddress)[0],
    method: "download_logo",
    args
  }] as const)
};
export const astroportXastroTokenQueries = {
  balance: <TData = BalanceResponse,>({
    client,
    args,
    options
  }: AstroportXastroTokenBalanceQuery<TData>): UseQueryOptions<BalanceResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.balance(client?.contractAddress, args),
    queryFn: () => client ? client.balance({
      address: args.address
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  balanceAt: <TData = BalanceResponse,>({
    client,
    args,
    options
  }: AstroportXastroTokenBalanceAtQuery<TData>): UseQueryOptions<BalanceResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.balanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.balanceAt({
      address: args.address,
      block: args.block
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  totalSupplyAt: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportXastroTokenTotalSupplyAtQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.totalSupplyAt(client?.contractAddress, args),
    queryFn: () => client ? client.totalSupplyAt({
      block: args.block
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  tokenInfo: <TData = TokenInfoResponse,>({
    client,
    options
  }: AstroportXastroTokenTokenInfoQuery<TData>): UseQueryOptions<TokenInfoResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.tokenInfo(client?.contractAddress),
    queryFn: () => client ? client.tokenInfo() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  minter: <TData = NullableMinterResponse,>({
    client,
    options
  }: AstroportXastroTokenMinterQuery<TData>): UseQueryOptions<NullableMinterResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.minter(client?.contractAddress),
    queryFn: () => client ? client.minter() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  allowance: <TData = AllowanceResponse,>({
    client,
    args,
    options
  }: AstroportXastroTokenAllowanceQuery<TData>): UseQueryOptions<AllowanceResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.allowance(client?.contractAddress, args),
    queryFn: () => client ? client.allowance({
      owner: args.owner,
      spender: args.spender
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  allAllowances: <TData = AllAllowancesResponse,>({
    client,
    args,
    options
  }: AstroportXastroTokenAllAllowancesQuery<TData>): UseQueryOptions<AllAllowancesResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.allAllowances(client?.contractAddress, args),
    queryFn: () => client ? client.allAllowances({
      limit: args.limit,
      owner: args.owner,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  allAccounts: <TData = AllAccountsResponse,>({
    client,
    args,
    options
  }: AstroportXastroTokenAllAccountsQuery<TData>): UseQueryOptions<AllAccountsResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.allAccounts(client?.contractAddress, args),
    queryFn: () => client ? client.allAccounts({
      limit: args.limit,
      startAfter: args.startAfter
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  marketingInfo: <TData = MarketingInfoResponse,>({
    client,
    options
  }: AstroportXastroTokenMarketingInfoQuery<TData>): UseQueryOptions<MarketingInfoResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.marketingInfo(client?.contractAddress),
    queryFn: () => client ? client.marketingInfo() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  downloadLogo: <TData = DownloadLogoResponse,>({
    client,
    options
  }: AstroportXastroTokenDownloadLogoQuery<TData>): UseQueryOptions<DownloadLogoResponse, Error, TData> => ({
    queryKey: astroportXastroTokenQueryKeys.downloadLogo(client?.contractAddress),
    queryFn: () => client ? client.downloadLogo() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportXastroTokenReactQuery<TResponse, TData = TResponse> {
  client: AstroportXastroTokenQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportXastroTokenDownloadLogoQuery<TData> extends AstroportXastroTokenReactQuery<DownloadLogoResponse, TData> {}
export function useAstroportXastroTokenDownloadLogoQuery<TData = DownloadLogoResponse>({
  client,
  options
}: AstroportXastroTokenDownloadLogoQuery<TData>) {
  return useQuery<DownloadLogoResponse, Error, TData>(astroportXastroTokenQueryKeys.downloadLogo(client?.contractAddress), () => client ? client.downloadLogo() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenMarketingInfoQuery<TData> extends AstroportXastroTokenReactQuery<MarketingInfoResponse, TData> {}
export function useAstroportXastroTokenMarketingInfoQuery<TData = MarketingInfoResponse>({
  client,
  options
}: AstroportXastroTokenMarketingInfoQuery<TData>) {
  return useQuery<MarketingInfoResponse, Error, TData>(astroportXastroTokenQueryKeys.marketingInfo(client?.contractAddress), () => client ? client.marketingInfo() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenAllAccountsQuery<TData> extends AstroportXastroTokenReactQuery<AllAccountsResponse, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useAstroportXastroTokenAllAccountsQuery<TData = AllAccountsResponse>({
  client,
  args,
  options
}: AstroportXastroTokenAllAccountsQuery<TData>) {
  return useQuery<AllAccountsResponse, Error, TData>(astroportXastroTokenQueryKeys.allAccounts(client?.contractAddress, args), () => client ? client.allAccounts({
    limit: args.limit,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenAllAllowancesQuery<TData> extends AstroportXastroTokenReactQuery<AllAllowancesResponse, TData> {
  args: {
    limit?: number;
    owner: string;
    startAfter?: string;
  };
}
export function useAstroportXastroTokenAllAllowancesQuery<TData = AllAllowancesResponse>({
  client,
  args,
  options
}: AstroportXastroTokenAllAllowancesQuery<TData>) {
  return useQuery<AllAllowancesResponse, Error, TData>(astroportXastroTokenQueryKeys.allAllowances(client?.contractAddress, args), () => client ? client.allAllowances({
    limit: args.limit,
    owner: args.owner,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenAllowanceQuery<TData> extends AstroportXastroTokenReactQuery<AllowanceResponse, TData> {
  args: {
    owner: string;
    spender: string;
  };
}
export function useAstroportXastroTokenAllowanceQuery<TData = AllowanceResponse>({
  client,
  args,
  options
}: AstroportXastroTokenAllowanceQuery<TData>) {
  return useQuery<AllowanceResponse, Error, TData>(astroportXastroTokenQueryKeys.allowance(client?.contractAddress, args), () => client ? client.allowance({
    owner: args.owner,
    spender: args.spender
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenMinterQuery<TData> extends AstroportXastroTokenReactQuery<NullableMinterResponse, TData> {}
export function useAstroportXastroTokenMinterQuery<TData = NullableMinterResponse>({
  client,
  options
}: AstroportXastroTokenMinterQuery<TData>) {
  return useQuery<NullableMinterResponse, Error, TData>(astroportXastroTokenQueryKeys.minter(client?.contractAddress), () => client ? client.minter() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenTokenInfoQuery<TData> extends AstroportXastroTokenReactQuery<TokenInfoResponse, TData> {}
export function useAstroportXastroTokenTokenInfoQuery<TData = TokenInfoResponse>({
  client,
  options
}: AstroportXastroTokenTokenInfoQuery<TData>) {
  return useQuery<TokenInfoResponse, Error, TData>(astroportXastroTokenQueryKeys.tokenInfo(client?.contractAddress), () => client ? client.tokenInfo() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenTotalSupplyAtQuery<TData> extends AstroportXastroTokenReactQuery<Uint128, TData> {
  args: {
    block: number;
  };
}
export function useAstroportXastroTokenTotalSupplyAtQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportXastroTokenTotalSupplyAtQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportXastroTokenQueryKeys.totalSupplyAt(client?.contractAddress, args), () => client ? client.totalSupplyAt({
    block: args.block
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenBalanceAtQuery<TData> extends AstroportXastroTokenReactQuery<BalanceResponse, TData> {
  args: {
    address: string;
    block: number;
  };
}
export function useAstroportXastroTokenBalanceAtQuery<TData = BalanceResponse>({
  client,
  args,
  options
}: AstroportXastroTokenBalanceAtQuery<TData>) {
  return useQuery<BalanceResponse, Error, TData>(astroportXastroTokenQueryKeys.balanceAt(client?.contractAddress, args), () => client ? client.balanceAt({
    address: args.address,
    block: args.block
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenBalanceQuery<TData> extends AstroportXastroTokenReactQuery<BalanceResponse, TData> {
  args: {
    address: string;
  };
}
export function useAstroportXastroTokenBalanceQuery<TData = BalanceResponse>({
  client,
  args,
  options
}: AstroportXastroTokenBalanceQuery<TData>) {
  return useQuery<BalanceResponse, Error, TData>(astroportXastroTokenQueryKeys.balance(client?.contractAddress, args), () => client ? client.balance({
    address: args.address
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportXastroTokenUploadLogoMutation {
  client: AstroportXastroTokenClient;
  msg: Logo;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenUploadLogoMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenUploadLogoMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenUploadLogoMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.uploadLogo(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenUpdateMarketingMutation {
  client: AstroportXastroTokenClient;
  msg: {
    description?: string;
    marketing?: string;
    project?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenUpdateMarketingMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenUpdateMarketingMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenUpdateMarketingMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateMarketing(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenUpdateMinterMutation {
  client: AstroportXastroTokenClient;
  msg: {
    newMinter?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenUpdateMinterMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenUpdateMinterMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenUpdateMinterMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateMinter(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenMintMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    recipient: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenMintMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenMintMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenMintMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.mint(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenBurnFromMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenBurnFromMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenBurnFromMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenBurnFromMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.burnFrom(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenSendFromMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    contract: string;
    msg: Binary;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenSendFromMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenSendFromMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenSendFromMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.sendFrom(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenTransferFromMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    owner: string;
    recipient: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenTransferFromMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenTransferFromMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenTransferFromMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.transferFrom(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenDecreaseAllowanceMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    expires?: Expiration;
    spender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenDecreaseAllowanceMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenDecreaseAllowanceMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenDecreaseAllowanceMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.decreaseAllowance(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenIncreaseAllowanceMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    expires?: Expiration;
    spender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenIncreaseAllowanceMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenIncreaseAllowanceMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenIncreaseAllowanceMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.increaseAllowance(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenSendMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    contract: string;
    msg: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenSendMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenSendMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenSendMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.send(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenBurnMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenBurnMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenBurnMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenBurnMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.burn(msg, fee, memo, funds), options);
}
export interface AstroportXastroTokenTransferMutation {
  client: AstroportXastroTokenClient;
  msg: {
    amount: Uint128;
    recipient: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportXastroTokenTransferMutation(options?: Omit<UseMutationOptions<any, Error, AstroportXastroTokenTransferMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportXastroTokenTransferMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.transfer(msg, fee, memo, funds), options);
}