/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { AssetInfo, Addr, Binary, PairType, InstantiateMsg, ExecuteMsg, Uint128, Decimal, Cw20ReceiveMsg, Asset, Empty, QueryMsg, Uint64, MigrateMsg, NullableUint128, Decimal256, ConfigResponse, CumulativePricesResponse, OracleObservation, PairInfo, PoolResponse, ReverseSimulationResponse, ArrayOfAsset, SimulationResponse } from "./AstroportPairConcentratedSaleTax.types";
import { AstroportPairConcentratedSaleTaxQueryClient, AstroportPairConcentratedSaleTaxClient } from "./AstroportPairConcentratedSaleTax.client";
export const astroportPairConcentratedSaleTaxQueryKeys = {
  contract: ([{
    contract: "astroportPairConcentratedSaleTax"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  pair: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "pair",
    args
  }] as const),
  pool: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "pool",
    args
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  share: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "share",
    args
  }] as const),
  simulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "simulation",
    args
  }] as const),
  reverseSimulation: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "reverse_simulation",
    args
  }] as const),
  cumulativePrices: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "cumulative_prices",
    args
  }] as const),
  computeD: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "compute_d",
    args
  }] as const),
  lpPrice: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "lp_price",
    args
  }] as const),
  assetBalanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "asset_balance_at",
    args
  }] as const),
  observe: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "observe",
    args
  }] as const),
  simulateProvide: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "simulate_provide",
    args
  }] as const),
  simulateWithdraw: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportPairConcentratedSaleTaxQueryKeys.address(contractAddress)[0],
    method: "simulate_withdraw",
    args
  }] as const)
};
export const astroportPairConcentratedSaleTaxQueries = {
  pair: <TData = PairInfo,>({
    client,
    options
  }: AstroportPairConcentratedSaleTaxPairQuery<TData>): UseQueryOptions<PairInfo, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.pair(client?.contractAddress),
    queryFn: () => client ? client.pair() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  pool: <TData = PoolResponse,>({
    client,
    options
  }: AstroportPairConcentratedSaleTaxPoolQuery<TData>): UseQueryOptions<PoolResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.pool(client?.contractAddress),
    queryFn: () => client ? client.pool() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportPairConcentratedSaleTaxConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  share: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSaleTaxShareQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.share(client?.contractAddress, args),
    queryFn: () => client ? client.share({
      amount: args.amount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulation: <TData = SimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSaleTaxSimulationQuery<TData>): UseQueryOptions<SimulationResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.simulation(client?.contractAddress, args),
    queryFn: () => client ? client.simulation({
      askAssetInfo: args.askAssetInfo,
      offerAsset: args.offerAsset
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseSimulation: <TData = ReverseSimulationResponse,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSaleTaxReverseSimulationQuery<TData>): UseQueryOptions<ReverseSimulationResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.reverseSimulation(client?.contractAddress, args),
    queryFn: () => client ? client.reverseSimulation({
      askAsset: args.askAsset,
      offerAssetInfo: args.offerAssetInfo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  cumulativePrices: <TData = CumulativePricesResponse,>({
    client,
    options
  }: AstroportPairConcentratedSaleTaxCumulativePricesQuery<TData>): UseQueryOptions<CumulativePricesResponse, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.cumulativePrices(client?.contractAddress),
    queryFn: () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  computeD: <TData = Decimal256,>({
    client,
    options
  }: AstroportPairConcentratedSaleTaxComputeDQuery<TData>): UseQueryOptions<Decimal256, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.computeD(client?.contractAddress),
    queryFn: () => client ? client.computeD() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  lpPrice: <TData = Decimal256,>({
    client,
    options
  }: AstroportPairConcentratedSaleTaxLpPriceQuery<TData>): UseQueryOptions<Decimal256, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.lpPrice(client?.contractAddress),
    queryFn: () => client ? client.lpPrice() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  assetBalanceAt: <TData = NullableUint128,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSaleTaxAssetBalanceAtQuery<TData>): UseQueryOptions<NullableUint128, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.assetBalanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.assetBalanceAt({
      assetInfo: args.assetInfo,
      blockHeight: args.blockHeight
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  observe: <TData = OracleObservation,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSaleTaxObserveQuery<TData>): UseQueryOptions<OracleObservation, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.observe(client?.contractAddress, args),
    queryFn: () => client ? client.observe({
      secondsAgo: args.secondsAgo
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateProvide: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSaleTaxSimulateProvideQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.simulateProvide(client?.contractAddress, args),
    queryFn: () => client ? client.simulateProvide({
      assets: args.assets,
      slippageTolerance: args.slippageTolerance
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateWithdraw: <TData = ArrayOfAsset,>({
    client,
    args,
    options
  }: AstroportPairConcentratedSaleTaxSimulateWithdrawQuery<TData>): UseQueryOptions<ArrayOfAsset, Error, TData> => ({
    queryKey: astroportPairConcentratedSaleTaxQueryKeys.simulateWithdraw(client?.contractAddress, args),
    queryFn: () => client ? client.simulateWithdraw({
      lpAmount: args.lpAmount
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportPairConcentratedSaleTaxReactQuery<TResponse, TData = TResponse> {
  client: AstroportPairConcentratedSaleTaxQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportPairConcentratedSaleTaxSimulateWithdrawQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<ArrayOfAsset, TData> {
  args: {
    lpAmount: Uint128;
  };
}
export function useAstroportPairConcentratedSaleTaxSimulateWithdrawQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairConcentratedSaleTaxSimulateWithdrawQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.simulateWithdraw(client?.contractAddress, args), () => client ? client.simulateWithdraw({
    lpAmount: args.lpAmount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxSimulateProvideQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<Uint128, TData> {
  args: {
    assets: Asset[];
    slippageTolerance?: Decimal;
  };
}
export function useAstroportPairConcentratedSaleTaxSimulateProvideQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportPairConcentratedSaleTaxSimulateProvideQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.simulateProvide(client?.contractAddress, args), () => client ? client.simulateProvide({
    assets: args.assets,
    slippageTolerance: args.slippageTolerance
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxObserveQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<OracleObservation, TData> {
  args: {
    secondsAgo: number;
  };
}
export function useAstroportPairConcentratedSaleTaxObserveQuery<TData = OracleObservation>({
  client,
  args,
  options
}: AstroportPairConcentratedSaleTaxObserveQuery<TData>) {
  return useQuery<OracleObservation, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.observe(client?.contractAddress, args), () => client ? client.observe({
    secondsAgo: args.secondsAgo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxAssetBalanceAtQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<NullableUint128, TData> {
  args: {
    assetInfo: AssetInfo;
    blockHeight: Uint64;
  };
}
export function useAstroportPairConcentratedSaleTaxAssetBalanceAtQuery<TData = NullableUint128>({
  client,
  args,
  options
}: AstroportPairConcentratedSaleTaxAssetBalanceAtQuery<TData>) {
  return useQuery<NullableUint128, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.assetBalanceAt(client?.contractAddress, args), () => client ? client.assetBalanceAt({
    assetInfo: args.assetInfo,
    blockHeight: args.blockHeight
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxLpPriceQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<Decimal256, TData> {}
export function useAstroportPairConcentratedSaleTaxLpPriceQuery<TData = Decimal256>({
  client,
  options
}: AstroportPairConcentratedSaleTaxLpPriceQuery<TData>) {
  return useQuery<Decimal256, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.lpPrice(client?.contractAddress), () => client ? client.lpPrice() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxComputeDQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<Decimal256, TData> {}
export function useAstroportPairConcentratedSaleTaxComputeDQuery<TData = Decimal256>({
  client,
  options
}: AstroportPairConcentratedSaleTaxComputeDQuery<TData>) {
  return useQuery<Decimal256, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.computeD(client?.contractAddress), () => client ? client.computeD() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxCumulativePricesQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<CumulativePricesResponse, TData> {}
export function useAstroportPairConcentratedSaleTaxCumulativePricesQuery<TData = CumulativePricesResponse>({
  client,
  options
}: AstroportPairConcentratedSaleTaxCumulativePricesQuery<TData>) {
  return useQuery<CumulativePricesResponse, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.cumulativePrices(client?.contractAddress), () => client ? client.cumulativePrices() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxReverseSimulationQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<ReverseSimulationResponse, TData> {
  args: {
    askAsset: Asset;
    offerAssetInfo?: AssetInfo;
  };
}
export function useAstroportPairConcentratedSaleTaxReverseSimulationQuery<TData = ReverseSimulationResponse>({
  client,
  args,
  options
}: AstroportPairConcentratedSaleTaxReverseSimulationQuery<TData>) {
  return useQuery<ReverseSimulationResponse, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.reverseSimulation(client?.contractAddress, args), () => client ? client.reverseSimulation({
    askAsset: args.askAsset,
    offerAssetInfo: args.offerAssetInfo
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxSimulationQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<SimulationResponse, TData> {
  args: {
    askAssetInfo?: AssetInfo;
    offerAsset: Asset;
  };
}
export function useAstroportPairConcentratedSaleTaxSimulationQuery<TData = SimulationResponse>({
  client,
  args,
  options
}: AstroportPairConcentratedSaleTaxSimulationQuery<TData>) {
  return useQuery<SimulationResponse, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.simulation(client?.contractAddress, args), () => client ? client.simulation({
    askAssetInfo: args.askAssetInfo,
    offerAsset: args.offerAsset
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxShareQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<ArrayOfAsset, TData> {
  args: {
    amount: Uint128;
  };
}
export function useAstroportPairConcentratedSaleTaxShareQuery<TData = ArrayOfAsset>({
  client,
  args,
  options
}: AstroportPairConcentratedSaleTaxShareQuery<TData>) {
  return useQuery<ArrayOfAsset, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.share(client?.contractAddress, args), () => client ? client.share({
    amount: args.amount
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxConfigQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<ConfigResponse, TData> {}
export function useAstroportPairConcentratedSaleTaxConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportPairConcentratedSaleTaxConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxPoolQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<PoolResponse, TData> {}
export function useAstroportPairConcentratedSaleTaxPoolQuery<TData = PoolResponse>({
  client,
  options
}: AstroportPairConcentratedSaleTaxPoolQuery<TData>) {
  return useQuery<PoolResponse, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.pool(client?.contractAddress), () => client ? client.pool() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxPairQuery<TData> extends AstroportPairConcentratedSaleTaxReactQuery<PairInfo, TData> {}
export function useAstroportPairConcentratedSaleTaxPairQuery<TData = PairInfo>({
  client,
  options
}: AstroportPairConcentratedSaleTaxPairQuery<TData>) {
  return useQuery<PairInfo, Error, TData>(astroportPairConcentratedSaleTaxQueryKeys.pair(client?.contractAddress), () => client ? client.pair() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportPairConcentratedSaleTaxCustomMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxCustomMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxCustomMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxCustomMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.custom(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxClaimOwnershipMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxClaimOwnershipMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxClaimOwnershipMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxClaimOwnershipMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.claimOwnership(fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxDropOwnershipProposalMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxDropOwnershipProposalMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxDropOwnershipProposalMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxDropOwnershipProposalMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.dropOwnershipProposal(fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxProposeNewOwnerMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  msg: {
    expiresIn: number;
    owner: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxProposeNewOwnerMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxProposeNewOwnerMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxProposeNewOwnerMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.proposeNewOwner(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxUpdateConfigMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  msg: {
    params: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxUpdateConfigMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxUpdateConfigMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxUpdateConfigMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.updateConfig(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxSwapMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  msg: {
    askAssetInfo?: AssetInfo;
    beliefPrice?: Decimal;
    maxSpread?: Decimal;
    offerAsset: Asset;
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxSwapMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxSwapMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxSwapMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.swap(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxWithdrawLiquidityMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  msg: {
    assets?: Asset[];
    minAssetsToReceive?: Asset[];
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxWithdrawLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxWithdrawLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxWithdrawLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.withdrawLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxProvideLiquidityMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  msg: {
    assets: Asset[];
    autoStake?: boolean;
    minLpToReceive?: Uint128;
    receiver?: string;
    slippageTolerance?: Decimal;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxProvideLiquidityMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxProvideLiquidityMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxProvideLiquidityMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.provideLiquidity(msg, fee, memo, funds), options);
}
export interface AstroportPairConcentratedSaleTaxReceiveMutation {
  client: AstroportPairConcentratedSaleTaxClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportPairConcentratedSaleTaxReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportPairConcentratedSaleTaxReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportPairConcentratedSaleTaxReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}