/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Uint128, Binary, Decimal, SwapOperation, AssetInfo, Addr, Cw20ReceiveMsg, QueryMsg, ConfigResponse, SimulateSwapOperationsResponse } from "./AstroportRouter.types";
import { AstroportRouterQueryClient, AstroportRouterClient } from "./AstroportRouter.client";
export const astroportRouterQueryKeys = {
  contract: ([{
    contract: "astroportRouter"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportRouterQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportRouterQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  simulateSwapOperations: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportRouterQueryKeys.address(contractAddress)[0],
    method: "simulate_swap_operations",
    args
  }] as const),
  reverseSimulateSwapOperations: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportRouterQueryKeys.address(contractAddress)[0],
    method: "reverse_simulate_swap_operations",
    args
  }] as const)
};
export const astroportRouterQueries = {
  config: <TData = ConfigResponse,>({
    client,
    options
  }: AstroportRouterConfigQuery<TData>): UseQueryOptions<ConfigResponse, Error, TData> => ({
    queryKey: astroportRouterQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  simulateSwapOperations: <TData = SimulateSwapOperationsResponse,>({
    client,
    args,
    options
  }: AstroportRouterSimulateSwapOperationsQuery<TData>): UseQueryOptions<SimulateSwapOperationsResponse, Error, TData> => ({
    queryKey: astroportRouterQueryKeys.simulateSwapOperations(client?.contractAddress, args),
    queryFn: () => client ? client.simulateSwapOperations({
      offerAmount: args.offerAmount,
      operations: args.operations
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  reverseSimulateSwapOperations: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportRouterReverseSimulateSwapOperationsQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportRouterQueryKeys.reverseSimulateSwapOperations(client?.contractAddress, args),
    queryFn: () => client ? client.reverseSimulateSwapOperations({
      askAmount: args.askAmount,
      operations: args.operations
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportRouterReactQuery<TResponse, TData = TResponse> {
  client: AstroportRouterQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportRouterReverseSimulateSwapOperationsQuery<TData> extends AstroportRouterReactQuery<Uint128, TData> {
  args: {
    askAmount: Uint128;
    operations: SwapOperation[];
  };
}
export function useAstroportRouterReverseSimulateSwapOperationsQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportRouterReverseSimulateSwapOperationsQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportRouterQueryKeys.reverseSimulateSwapOperations(client?.contractAddress, args), () => client ? client.reverseSimulateSwapOperations({
    askAmount: args.askAmount,
    operations: args.operations
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportRouterSimulateSwapOperationsQuery<TData> extends AstroportRouterReactQuery<SimulateSwapOperationsResponse, TData> {
  args: {
    offerAmount: Uint128;
    operations: SwapOperation[];
  };
}
export function useAstroportRouterSimulateSwapOperationsQuery<TData = SimulateSwapOperationsResponse>({
  client,
  args,
  options
}: AstroportRouterSimulateSwapOperationsQuery<TData>) {
  return useQuery<SimulateSwapOperationsResponse, Error, TData>(astroportRouterQueryKeys.simulateSwapOperations(client?.contractAddress, args), () => client ? client.simulateSwapOperations({
    offerAmount: args.offerAmount,
    operations: args.operations
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportRouterConfigQuery<TData> extends AstroportRouterReactQuery<ConfigResponse, TData> {}
export function useAstroportRouterConfigQuery<TData = ConfigResponse>({
  client,
  options
}: AstroportRouterConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(astroportRouterQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportRouterExecuteSwapOperationMutation {
  client: AstroportRouterClient;
  msg: {
    maxSpread?: Decimal;
    operation: SwapOperation;
    single: boolean;
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportRouterExecuteSwapOperationMutation(options?: Omit<UseMutationOptions<any, Error, AstroportRouterExecuteSwapOperationMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportRouterExecuteSwapOperationMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.executeSwapOperation(msg, fee, memo, funds), options);
}
export interface AstroportRouterExecuteSwapOperationsMutation {
  client: AstroportRouterClient;
  msg: {
    maxSpread?: Decimal;
    minimumReceive?: Uint128;
    operations: SwapOperation[];
    to?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportRouterExecuteSwapOperationsMutation(options?: Omit<UseMutationOptions<any, Error, AstroportRouterExecuteSwapOperationsMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportRouterExecuteSwapOperationsMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.executeSwapOperations(msg, fee, memo, funds), options);
}
export interface AstroportRouterReceiveMutation {
  client: AstroportRouterClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportRouterReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportRouterReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportRouterReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}