/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { StdFee, Coin } from "@interchainjs/types";
import { useMutation, UseMutationOptions } from "@tanstack/react-query";
import { AssetInfo, Addr, InstantiateMsg, OutpostBurnParams, ExecuteMsg, Uint128, Binary, Cw20ReceiveMsg } from "./AstroTokenConverter.types";
import { AstroTokenConverterClient } from "./AstroTokenConverter.client";
export interface AstroTokenConverterBurnMutation {
  client: AstroTokenConverterClient;
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroTokenConverterBurnMutation(options?: Omit<UseMutationOptions<any, Error, AstroTokenConverterBurnMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroTokenConverterBurnMutation>(({
    client,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.burn(fee, memo, funds), options);
}
export interface AstroTokenConverterTransferForBurningMutation {
  client: AstroTokenConverterClient;
  msg: {
    timeout?: number;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroTokenConverterTransferForBurningMutation(options?: Omit<UseMutationOptions<any, Error, AstroTokenConverterTransferForBurningMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroTokenConverterTransferForBurningMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.transferForBurning(msg, fee, memo, funds), options);
}
export interface AstroTokenConverterReceiveMutation {
  client: AstroTokenConverterClient;
  msg: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroTokenConverterReceiveMutation(options?: Omit<UseMutationOptions<any, Error, AstroTokenConverterReceiveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroTokenConverterReceiveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.receive(msg, fee, memo, funds), options);
}
export interface AstroTokenConverterConvertMutation {
  client: AstroTokenConverterClient;
  msg: {
    receiver?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroTokenConverterConvertMutation(options?: Omit<UseMutationOptions<any, Error, AstroTokenConverterConvertMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroTokenConverterConvertMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.convert(msg, fee, memo, funds), options);
}