/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin, StdFee } from "@interchainjs/types";
import { ISigningCosmWasmClient } from "./baseClient";
import { AssetInfo, Addr, InstantiateMsg, OutpostBurnParams, ExecuteMsg, Uint128, Binary, Cw20ReceiveMsg } from "./AstroTokenConverter.types";
export interface AstroTokenConverterInterface {
  contractAddress: string;
  sender: string;
  convert: ({
    receiver
  }: {
    receiver?: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  receive: ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  transferForBurning: ({
    timeout
  }: {
    timeout?: number;
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  burn: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroTokenConverterClient implements AstroTokenConverterInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.convert = this.convert.bind(this);
    this.receive = this.receive.bind(this);
    this.transferForBurning = this.transferForBurning.bind(this);
    this.burn = this.burn.bind(this);
  }
  convert = async ({
    receiver
  }: {
    receiver?: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      convert: {
        receiver
      }
    }, fee_, memo_, funds_);
  };
  receive = async ({
    amount,
    msg,
    sender
  }: {
    amount: Uint128;
    msg: Binary;
    sender: string;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      receive: {
        amount,
        msg,
        sender
      }
    }, fee_, memo_, funds_);
  };
  transferForBurning = async ({
    timeout
  }: {
    timeout?: number;
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      transfer_for_burning: {
        timeout
      }
    }, fee_, memo_, funds_);
  };
  burn = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      burn: {}
    }, fee_, memo_, funds_);
  };
}