/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ICosmWasmClient, ISigningCosmWasmClient } from "./baseClient";
import { StdFee } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, CosmosMsgForNeutronMsg, BankMsg, Uint128, NeutronMsg, Binary, AdminProposal, StakingMsg, DistributionMsg, IbcMsg, Timestamp, Uint64, WasmMsg, GovMsg, VoteOption, Coin, IbcFee, ProtobufAny, KVKey, RequestPacketTimeoutHeight, ParamChangeProposal, ParamChange, UpgradeProposal, Plan, ClientUpdateProposal, ProposalExecuteMessage, SoftwareUpgradeProposal, CancelSoftwareUpgradeProposal, PinCodesProposal, UnpinCodesProposal, SudoContractProposal, UpdateAdminProposal, ClearAdminProposal, DenomUnit, MsgExecuteContract, IbcTimeout, IbcTimeoutBlock, QueryMsg, CosmosMsgForEmpty, Empty, AdminListResponse, CanExecuteResponse } from "./AstroportWhitelist.types";
export interface AstroportWhitelistReadOnlyInterface {
  contractAddress: string;
  adminList: () => Promise<AdminListResponse>;
  canExecute: ({
    msg,
    sender
  }: {
    msg: CosmosMsgForEmpty;
    sender: string;
  }) => Promise<CanExecuteResponse>;
}
export class AstroportWhitelistQueryClient implements AstroportWhitelistReadOnlyInterface {
  client: ICosmWasmClient;
  contractAddress: string;
  constructor(client: ICosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.adminList = this.adminList.bind(this);
    this.canExecute = this.canExecute.bind(this);
  }
  adminList = async (): Promise<AdminListResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      admin_list: {}
    });
  };
  canExecute = async ({
    msg,
    sender
  }: {
    msg: CosmosMsgForEmpty;
    sender: string;
  }): Promise<CanExecuteResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      can_execute: {
        msg,
        sender
      }
    });
  };
}
export interface AstroportWhitelistInterface {
  contractAddress: string;
  sender: string;
  execute: ({
    msgs
  }: {
    msgs: CosmosMsgForNeutronMsg[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  freeze: (fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
  updateAdmins: ({
    admins
  }: {
    admins: string[];
  }, fee_?: number | StdFee | "auto", memo_?: string, funds_?: Coin[]) => Promise<any>;
}
export class AstroportWhitelistClient implements AstroportWhitelistInterface {
  client: ISigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: ISigningCosmWasmClient, sender: string, contractAddress: string) {
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.execute = this.execute.bind(this);
    this.freeze = this.freeze.bind(this);
    this.updateAdmins = this.updateAdmins.bind(this);
  }
  execute = async ({
    msgs
  }: {
    msgs: CosmosMsgForNeutronMsg[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      execute: {
        msgs
      }
    }, fee_, memo_, funds_);
  };
  freeze = async (fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      freeze: {}
    }, fee_, memo_, funds_);
  };
  updateAdmins = async ({
    admins
  }: {
    admins: string[];
  }, fee_: number | StdFee | "auto" = "auto", memo_?: string, funds_?: Coin[]): Promise<any> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_admins: {
        admins
      }
    }, fee_, memo_, funds_);
  };
}