/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery, useMutation, UseMutationOptions } from "@tanstack/react-query";
import { StdFee, Coin } from "@interchainjs/types";
import { InstantiateMsg, ExecuteMsg, Binary, QueryMsg, Uint128, Config, TrackerData } from "./AstroportStaking.types";
import { AstroportStakingQueryClient, AstroportStakingClient } from "./AstroportStaking.client";
export const astroportStakingQueryKeys = {
  contract: ([{
    contract: "astroportStaking"
  }] as const),
  address: (contractAddress: string | undefined) => ([{
    ...astroportStakingQueryKeys.contract[0],
    address: contractAddress
  }] as const),
  config: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportStakingQueryKeys.address(contractAddress)[0],
    method: "config",
    args
  }] as const),
  totalShares: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportStakingQueryKeys.address(contractAddress)[0],
    method: "total_shares",
    args
  }] as const),
  totalDeposit: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportStakingQueryKeys.address(contractAddress)[0],
    method: "total_deposit",
    args
  }] as const),
  trackerConfig: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportStakingQueryKeys.address(contractAddress)[0],
    method: "tracker_config",
    args
  }] as const),
  balanceAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportStakingQueryKeys.address(contractAddress)[0],
    method: "balance_at",
    args
  }] as const),
  totalSupplyAt: (contractAddress: string | undefined, args?: Record<string, unknown>) => ([{
    ...astroportStakingQueryKeys.address(contractAddress)[0],
    method: "total_supply_at",
    args
  }] as const)
};
export const astroportStakingQueries = {
  config: <TData = Config,>({
    client,
    options
  }: AstroportStakingConfigQuery<TData>): UseQueryOptions<Config, Error, TData> => ({
    queryKey: astroportStakingQueryKeys.config(client?.contractAddress),
    queryFn: () => client ? client.config() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  totalShares: <TData = Uint128,>({
    client,
    options
  }: AstroportStakingTotalSharesQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportStakingQueryKeys.totalShares(client?.contractAddress),
    queryFn: () => client ? client.totalShares() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  totalDeposit: <TData = Uint128,>({
    client,
    options
  }: AstroportStakingTotalDepositQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportStakingQueryKeys.totalDeposit(client?.contractAddress),
    queryFn: () => client ? client.totalDeposit() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  trackerConfig: <TData = TrackerData,>({
    client,
    options
  }: AstroportStakingTrackerConfigQuery<TData>): UseQueryOptions<TrackerData, Error, TData> => ({
    queryKey: astroportStakingQueryKeys.trackerConfig(client?.contractAddress),
    queryFn: () => client ? client.trackerConfig() : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  balanceAt: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportStakingBalanceAtQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportStakingQueryKeys.balanceAt(client?.contractAddress, args),
    queryFn: () => client ? client.balanceAt({
      address: args.address,
      timestamp: args.timestamp
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  }),
  totalSupplyAt: <TData = Uint128,>({
    client,
    args,
    options
  }: AstroportStakingTotalSupplyAtQuery<TData>): UseQueryOptions<Uint128, Error, TData> => ({
    queryKey: astroportStakingQueryKeys.totalSupplyAt(client?.contractAddress, args),
    queryFn: () => client ? client.totalSupplyAt({
      timestamp: args.timestamp
    }) : Promise.reject(new Error("Invalid client")),
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  })
};
export interface AstroportStakingReactQuery<TResponse, TData = TResponse> {
  client: AstroportStakingQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface AstroportStakingTotalSupplyAtQuery<TData> extends AstroportStakingReactQuery<Uint128, TData> {
  args: {
    timestamp?: number;
  };
}
export function useAstroportStakingTotalSupplyAtQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportStakingTotalSupplyAtQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportStakingQueryKeys.totalSupplyAt(client?.contractAddress, args), () => client ? client.totalSupplyAt({
    timestamp: args.timestamp
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportStakingBalanceAtQuery<TData> extends AstroportStakingReactQuery<Uint128, TData> {
  args: {
    address: string;
    timestamp?: number;
  };
}
export function useAstroportStakingBalanceAtQuery<TData = Uint128>({
  client,
  args,
  options
}: AstroportStakingBalanceAtQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportStakingQueryKeys.balanceAt(client?.contractAddress, args), () => client ? client.balanceAt({
    address: args.address,
    timestamp: args.timestamp
  }) : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportStakingTrackerConfigQuery<TData> extends AstroportStakingReactQuery<TrackerData, TData> {}
export function useAstroportStakingTrackerConfigQuery<TData = TrackerData>({
  client,
  options
}: AstroportStakingTrackerConfigQuery<TData>) {
  return useQuery<TrackerData, Error, TData>(astroportStakingQueryKeys.trackerConfig(client?.contractAddress), () => client ? client.trackerConfig() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportStakingTotalDepositQuery<TData> extends AstroportStakingReactQuery<Uint128, TData> {}
export function useAstroportStakingTotalDepositQuery<TData = Uint128>({
  client,
  options
}: AstroportStakingTotalDepositQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportStakingQueryKeys.totalDeposit(client?.contractAddress), () => client ? client.totalDeposit() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportStakingTotalSharesQuery<TData> extends AstroportStakingReactQuery<Uint128, TData> {}
export function useAstroportStakingTotalSharesQuery<TData = Uint128>({
  client,
  options
}: AstroportStakingTotalSharesQuery<TData>) {
  return useQuery<Uint128, Error, TData>(astroportStakingQueryKeys.totalShares(client?.contractAddress), () => client ? client.totalShares() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportStakingConfigQuery<TData> extends AstroportStakingReactQuery<Config, TData> {}
export function useAstroportStakingConfigQuery<TData = Config>({
  client,
  options
}: AstroportStakingConfigQuery<TData>) {
  return useQuery<Config, Error, TData>(astroportStakingQueryKeys.config(client?.contractAddress), () => client ? client.config() : Promise.reject(new Error("Invalid client")), {
    ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface AstroportStakingLeaveMutation {
  client: AstroportStakingClient;
  msg: {
    receiver?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportStakingLeaveMutation(options?: Omit<UseMutationOptions<any, Error, AstroportStakingLeaveMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportStakingLeaveMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.leave(msg, fee, memo, funds), options);
}
export interface AstroportStakingEnterWithHookMutation {
  client: AstroportStakingClient;
  msg: {
    contractAddress: string;
    msg: Binary;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportStakingEnterWithHookMutation(options?: Omit<UseMutationOptions<any, Error, AstroportStakingEnterWithHookMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportStakingEnterWithHookMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.enterWithHook(msg, fee, memo, funds), options);
}
export interface AstroportStakingEnterMutation {
  client: AstroportStakingClient;
  msg: {
    receiver?: string;
  };
  args?: {
    fee?: number | StdFee | "auto";
    memo?: string;
    funds?: Coin[];
  };
}
export function useAstroportStakingEnterMutation(options?: Omit<UseMutationOptions<any, Error, AstroportStakingEnterMutation>, "mutationFn">) {
  return useMutation<any, Error, AstroportStakingEnterMutation>(({
    client,
    msg,
    args: {
      fee,
      memo,
      funds
    } = {}
  }) => client.enter(msg, fee, memo, funds), options);
}