/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.14.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./AstroportNativeCoinRegistry.types";
import * as _1 from "./AstroportNativeCoinRegistry.client";
import * as _2 from "./AstroportNativeCoinRegistry.react-query";
import * as _3 from "./AstroportPairXykSaleTax.types";
import * as _4 from "./AstroportPairXykSaleTax.client";
import * as _5 from "./AstroportPairXykSaleTax.react-query";
import * as _6 from "./AstroportPairConcentrated.types";
import * as _7 from "./AstroportPairConcentrated.client";
import * as _8 from "./AstroportPairConcentrated.react-query";
import * as _9 from "./AstroportMaker.types";
import * as _10 from "./AstroportMaker.client";
import * as _11 from "./AstroportMaker.react-query";
import * as _12 from "./AstroportPairStable.types";
import * as _13 from "./AstroportPairStable.client";
import * as _14 from "./AstroportPairStable.react-query";
import * as _15 from "./AstroportRouter.types";
import * as _16 from "./AstroportRouter.client";
import * as _17 from "./AstroportRouter.react-query";
import * as _18 from "./AstroportFactory.types";
import * as _19 from "./AstroportFactory.client";
import * as _20 from "./AstroportFactory.react-query";
import * as _21 from "./AstroportPairConcentratedSaleTax.types";
import * as _22 from "./AstroportPairConcentratedSaleTax.client";
import * as _23 from "./AstroportPairConcentratedSaleTax.react-query";
import * as _24 from "./AstroportPairConcentratedDuality.types";
import * as _25 from "./AstroportPairConcentratedDuality.client";
import * as _26 from "./AstroportPairConcentratedDuality.react-query";
import * as _27 from "./AstroportStaking.types";
import * as _28 from "./AstroportStaking.client";
import * as _29 from "./AstroportStaking.react-query";
import * as _30 from "./AstroTokenConverter.types";
import * as _31 from "./AstroTokenConverter.client";
import * as _32 from "./AstroTokenConverter.react-query";
import * as _33 from "./AstroportXastroToken.types";
import * as _34 from "./AstroportXastroToken.client";
import * as _35 from "./AstroportXastroToken.react-query";
import * as _36 from "./AstroportIncentives.types";
import * as _37 from "./AstroportIncentives.client";
import * as _38 from "./AstroportIncentives.react-query";
import * as _39 from "./AstroportOracle.types";
import * as _40 from "./AstroportOracle.client";
import * as _41 from "./AstroportOracle.react-query";
import * as _42 from "./AstroportTokenfactoryTracker.types";
import * as _43 from "./AstroportTokenfactoryTracker.client";
import * as _44 from "./AstroportTokenfactoryTracker.react-query";
import * as _45 from "./AstroportPairXastro.types";
import * as _46 from "./AstroportPairXastro.client";
import * as _47 from "./AstroportPairXastro.react-query";
import * as _48 from "./AstroportPair.types";
import * as _49 from "./AstroportPair.client";
import * as _50 from "./AstroportPair.react-query";
import * as _51 from "./AstroportPairConverter.types";
import * as _52 from "./AstroportPairConverter.client";
import * as _53 from "./AstroportPairConverter.react-query";
import * as _54 from "./AstroportWhitelist.types";
import * as _55 from "./AstroportWhitelist.client";
import * as _56 from "./AstroportWhitelist.react-query";
import * as _57 from "./AstroportVesting.types";
import * as _58 from "./AstroportVesting.client";
import * as _59 from "./AstroportVesting.react-query";
import * as _60 from "./baseClient";
export namespace Astroport {
  export const AstroportNativeCoinRegistry = {
    ..._0,
    ..._1,
    ..._2
  };
  export const AstroportPairXykSaleTax = {
    ..._3,
    ..._4,
    ..._5
  };
  export const AstroportPairConcentrated = {
    ..._6,
    ..._7,
    ..._8
  };
  export const AstroportMaker = {
    ..._9,
    ..._10,
    ..._11
  };
  export const AstroportPairStable = {
    ..._12,
    ..._13,
    ..._14
  };
  export const AstroportRouter = {
    ..._15,
    ..._16,
    ..._17
  };
  export const AstroportFactory = {
    ..._18,
    ..._19,
    ..._20
  };
  export const AstroportPairConcentratedSaleTax = {
    ..._21,
    ..._22,
    ..._23
  };
  export const AstroportPairConcentratedDuality = {
    ..._24,
    ..._25,
    ..._26
  };
  export const AstroportStaking = {
    ..._27,
    ..._28,
    ..._29
  };
  export const AstroTokenConverter = {
    ..._30,
    ..._31,
    ..._32
  };
  export const AstroportXastroToken = {
    ..._33,
    ..._34,
    ..._35
  };
  export const AstroportIncentives = {
    ..._36,
    ..._37,
    ..._38
  };
  export const AstroportOracle = {
    ..._39,
    ..._40,
    ..._41
  };
  export const AstroportTokenfactoryTracker = {
    ..._42,
    ..._43,
    ..._44
  };
  export const AstroportPairXastro = {
    ..._45,
    ..._46,
    ..._47
  };
  export const AstroportPair = {
    ..._48,
    ..._49,
    ..._50
  };
  export const AstroportPairConverter = {
    ..._51,
    ..._52,
    ..._53
  };
  export const AstroportWhitelist = {
    ..._54,
    ..._55,
    ..._56
  };
  export const AstroportVesting = {
    ..._57,
    ..._58,
    ..._59
  };
  export const baseClient = {
    ..._60
  };
}